"""Model mapping for EV DC R290 Heat Pump (000004jong)."""

MODEL_NAME = "Power World PW030 Heat Pump (000004jong)"
# ====================================================
# Power World PW030 @HeideggerDaniel
# ====================================================
SENSOR_TYPES = {
    # Inlet Water Temperature (dp_id: 101)
    "intemp": {
        "dp_id": 101,
        "code": "intemp",
        "name": "Inlet Water Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer-water",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    # Outlet Water Temperature (dp_id: 102)
    "outtemp": {
        "dp_id": 102,
        "code": "outtemp",
        "name": "Outlet Water Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer-water",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    # Ambient Temperature (dp_id: 103)
    "whjtemp": {
        "dp_id": 103,
        "code": "whjtemp",
        "name": "Ambient Temperature",
        "unit": "°C",
        "icon": "mdi:home-thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    # Exhaust / Discharge Temperature (dp_id: 104)
    "cmptemp": {
        "dp_id": 104,
        "code": "cmptemp",
        "name": "Exhaust Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer-alert",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    # Suction / Return Gas Temperature (dp_id: 105)
    "hqtemp": {
        "dp_id": 105,
        "code": "hqtemp",
        "name": "Suction Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    # Outdoor Coil Temperature (dp_id: 106)
    "ptemp": {
        "dp_id": 106,
        "code": "ptemp",
        "name": "Outdoor Coil Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    # Cooling Coil Temperature (dp_id: 107)
    "cptemp": {
        "dp_id": 107,
        "code": "cptemp",
        "name": "Cooling Coil Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    # Tank / Water Tank Temperature (dp_id: 108)
    "wttemp": {
        "dp_id": 108,
        "code": "wttemp",
        "name": "Water Tank Temperature",
        "unit": "°C",
        "icon": "mdi:water-thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    # Main Expansion Valve Opening (dp_id: 109)
    "step_run": {
        "dp_id": 109,
        "code": "step_run",
        "name": "Main Expansion Valve Opening",
        "unit": "P",
        "icon": "mdi:pipe-valve",
        "state_class": "measurement",
    },
    # Enthalpy Expansion Valve Opening (dp_id: 111)
    "stepb_run": {
        "dp_id": 111,
        "code": "stepb_run",
        "name": "Enthalpy Expansion Valve Opening",
        "unit": "P",
        "icon": "mdi:pipe-valve",
        "state_class": "measurement",
    },
    # Compressor Current (dp_id: 112)
    "cmp_cur": {
        "dp_id": 112,
        "code": "cmp_cur",
        "name": "Compressor Current",
        "unit": "A",
        "icon": "mdi:current-ac",
        "device_class": "current",
        "state_class": "measurement",
    },
    # Heatsink Temperature (dp_id: 113)
    "sink_temp": {
        "dp_id": 113,
        "code": "sink_temp",
        "name": "Heatsink Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    # DC Bus Voltage (dp_id: 114)
    "dc_bus_voltage": {
        "dp_id": 114,
        "code": "dc_bus_voltage",
        "name": "DC Bus Voltage",
        "unit": "V",
        "icon": "mdi:lightning-bolt",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    # Compressor Actual Frequency (dp_id: 115)
    "cmp_act_frep": {
        "dp_id": 115,
        "code": "cmp_act_frep",
        "name": "Compressor Frequency",
        "unit": "Hz",
        "icon": "mdi:sine-wave",
        "state_class": "measurement",
    },
    # DC Fan 1 Speed (dp_id: 116)
    "dc_fan_speed": {
        "dp_id": 116,
        "code": "dc_fan_speed",
        "name": "DC Fan 1 Speed",
        "unit": "RPM",
        "icon": "mdi:fan",
        "state_class": "measurement",
    },
    # DC Fan 2 Speed (dp_id: 117)
    "dc_fan2_speed": {
        "dp_id": 117,
        "code": "dc_fan2_speed",
        "name": "DC Fan 2 Speed",
        "unit": "RPM",
        "icon": "mdi:fan",
        "state_class": "measurement",
    },
    # Fault Code - Raw Bitmap Value (dp_id: 15)
    "fault_code": {
        "dp_id": 15,
        "code": "fault_code",
        "name": "Fault Code",
        "icon": "mdi:alert-circle",
        "device_class": "problem",
        "state_class": "measurement",
    },

    # ================================================
    # Raw-field sensors from parameter groups (dp 118-124)
    # Mapping contributed by a German user via raw_explorer.py.
    # Names have been translated to English for international use.
    # Many of these are internal factory settings ("factory default");
    # they are read-only and expose the device's configuration state.
    # ================================================
    "temperature_difference_return_water_and_cooling_water": {
        "dp_id": 118,
        "code": "temperature_difference_return_water_and_cooling_water",
        "raw_source": "parameter_group_1",
        "field_index": 0,
        "encoding": "int32_be",
        "name": "Temperature Difference Return Water and Cooling Water",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "temperature_difference_return_water_and_hot_water": {
        "dp_id": 118,
        "code": "temperature_difference_return_water_and_hot_water",
        "raw_source": "parameter_group_1",
        "field_index": 1,
        "encoding": "int32_be",
        "name": "Temperature Difference Return Water and Hot Water",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "hot_water_temperature": {
        "dp_id": 118,
        "code": "hot_water_temperature",
        "raw_source": "parameter_group_1",
        "field_index": 2,
        "encoding": "int32_be",
        "name": "Hot Water Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "cooling_temperature": {
        "dp_id": 118,
        "code": "cooling_temperature",
        "raw_source": "parameter_group_1",
        "field_index": 3,
        "encoding": "int32_be",
        "name": "Cooling Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "heating_temperature": {
        "dp_id": 118,
        "code": "heating_temperature",
        "raw_source": "parameter_group_1",
        "field_index": 4,
        "encoding": "int32_be",
        "name": "Heating Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "water_temperature_compensation": {
        "dp_id": 118,
        "code": "water_temperature_compensation",
        "raw_source": "parameter_group_1",
        "field_index": 5,
        "encoding": "int32_be",
        "name": "Water Temperature Compensation",
    },
    "disinfection_cycle_in_days": {
        "dp_id": 118,
        "code": "disinfection_cycle_in_days",
        "raw_source": "parameter_group_1",
        "field_index": 6,
        "encoding": "int32_be",
        "name": "Disinfection Cycle in Days",
    },
    "disinfection_start_time": {
        "dp_id": 118,
        "code": "disinfection_start_time",
        "raw_source": "parameter_group_1",
        "field_index": 7,
        "encoding": "int32_be",
        "name": "Disinfection Start Time",
    },
    "disinfection_duration": {
        "dp_id": 118,
        "code": "disinfection_duration",
        "raw_source": "parameter_group_1",
        "field_index": 8,
        "encoding": "int32_be",
        "name": "Disinfection Duration",
        "unit": "min",
    },
    "disinfection_temperature": {
        "dp_id": 118,
        "code": "disinfection_temperature",
        "raw_source": "parameter_group_1",
        "field_index": 9,
        "encoding": "int32_be",
        "name": "Disinfection Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "disinfection_set_temperature": {
        "dp_id": 118,
        "code": "disinfection_set_temperature",
        "raw_source": "parameter_group_1",
        "field_index": 10,
        "encoding": "int32_be",
        "name": "Disinfection Set Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "heating_setpoint_automatic_adjustment": {
        "dp_id": 118,
        "code": "heating_setpoint_automatic_adjustment",
        "raw_source": "parameter_group_1",
        "field_index": 11,
        "encoding": "int32_be",
        "name": "Heating Setpoint Automatic Adjustment",
    },
    "compensation_temperature_point": {
        "dp_id": 118,
        "code": "compensation_temperature_point",
        "raw_source": "parameter_group_1",
        "field_index": 12,
        "encoding": "int32_be",
        "name": "Compensation Temperature Point",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "target_temperature_coefficient": {
        "dp_id": 118,
        "code": "target_temperature_coefficient",
        "raw_source": "parameter_group_1",
        "field_index": 13,
        "encoding": "int32_be",
        "name": "Target Temperature Coefficient",
    },
    "downclocking": {
        "dp_id": 118,
        "code": "downclocking",
        "raw_source": "parameter_group_1",
        "field_index": 14,
        "encoding": "int32_be",
        "name": "Downclocking",
    },
    "heater_temperature_activation": {
        "dp_id": 118,
        "code": "heater_temperature_activation",
        "raw_source": "parameter_group_1",
        "field_index": 15,
        "encoding": "int32_be",
        "name": "Heater Temperature Activation",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "heater_delay_before_activation": {
        "dp_id": 118,
        "code": "heater_delay_before_activation",
        "raw_source": "parameter_group_1",
        "field_index": 16,
        "encoding": "int32_be",
        "name": "Heater Delay Before Activation",
    },
    "heat_pump_function": {
        "dp_id": 118,
        "code": "heat_pump_function",
        "raw_source": "parameter_group_1",
        "field_index": 17,
        "encoding": "int32_be",
        "name": "Heat Pump Function",
    },
    "circulation_pump_status_after_target_temperature_reached": {
        "dp_id": 118,
        "code": "circulation_pump_status_after_target_temperature_reached",
        "raw_source": "parameter_group_1",
        "field_index": 18,
        "encoding": "int32_be",
        "name": "Circulation Pump Status After Target Temperature Reached",
    },
    "circulation_pump_on_off_interval": {
        "dp_id": 118,
        "code": "circulation_pump_on_off_interval",
        "raw_source": "parameter_group_1",
        "field_index": 19,
        "encoding": "int32_be",
        "name": "Circulation Pump On/Off Interval",
    },
    "dc_circulation_pump": {
        "dp_id": 119,
        "code": "dc_circulation_pump",
        "raw_source": "parameter_group_2",
        "field_index": 0,
        "encoding": "int32_be",
        "name": "DC Circulation Pump",
    },
    "dc_circulation_pump_speed": {
        "dp_id": 119,
        "code": "dc_circulation_pump_speed",
        "raw_source": "parameter_group_2",
        "field_index": 1,
        "encoding": "int32_be",
        "name": "DC Circulation Pump Speed",
        "unit": "%",
        "icon": "mdi:percent",
    },
    "factory_default_defrost_interval": {
        "dp_id": 119,
        "code": "factory_default_defrost_interval",
        "raw_source": "parameter_group_2",
        "field_index": 2,
        "encoding": "int32_be",
        "name": "Factory Default - Defrost Interval",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_defrost_period": {
        "dp_id": 119,
        "code": "factory_default_defrost_period",
        "raw_source": "parameter_group_2",
        "field_index": 3,
        "encoding": "int32_be",
        "name": "Factory Default - Defrost Period",
        "unit": "min",
    },
    "factory_default_defrost_start_temperature": {
        "dp_id": 119,
        "code": "factory_default_defrost_start_temperature",
        "raw_source": "parameter_group_2",
        "field_index": 4,
        "encoding": "int32_be",
        "name": "Factory Default - Defrost Start Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "factory_default_defrost_duration": {
        "dp_id": 119,
        "code": "factory_default_defrost_duration",
        "raw_source": "parameter_group_2",
        "field_index": 5,
        "encoding": "int32_be",
        "name": "Factory Default - Defrost Duration",
        "unit": "min",
    },
    "factory_default_defrost_end_temperature": {
        "dp_id": 119,
        "code": "factory_default_defrost_end_temperature",
        "raw_source": "parameter_group_2",
        "field_index": 6,
        "encoding": "int32_be",
        "name": "Factory Default - Defrost End Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "factory_default_evaporator_temperature_difference_1": {
        "dp_id": 119,
        "code": "factory_default_evaporator_temperature_difference_1",
        "raw_source": "parameter_group_2",
        "field_index": 7,
        "encoding": "int32_be",
        "name": "Factory Default - Evaporator Temperature Difference 1",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "factory_default_evaporator_temperature_difference_2": {
        "dp_id": 119,
        "code": "factory_default_evaporator_temperature_difference_2",
        "raw_source": "parameter_group_2",
        "field_index": 8,
        "encoding": "int32_be",
        "name": "Factory Default - Evaporator Temperature Difference 2",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "factory_default_ambient_temperature_defrost_phase": {
        "dp_id": 119,
        "code": "factory_default_ambient_temperature_defrost_phase",
        "raw_source": "parameter_group_2",
        "field_index": 9,
        "encoding": "int32_be",
        "name": "Factory Default - Ambient Temperature Defrost Phase",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "factory_default_frequency_1": {
        "dp_id": 119,
        "code": "factory_default_frequency_1",
        "raw_source": "parameter_group_2",
        "field_index": 10,
        "encoding": "int32_be",
        "name": "Factory Default - Frequency 1",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_frequency_2": {
        "dp_id": 119,
        "code": "factory_default_frequency_2",
        "raw_source": "parameter_group_2",
        "field_index": 11,
        "encoding": "int32_be",
        "name": "Factory Default - Frequency 2",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_frequency_3": {
        "dp_id": 119,
        "code": "factory_default_frequency_3",
        "raw_source": "parameter_group_2",
        "field_index": 12,
        "encoding": "int32_be",
        "name": "Factory Default - Frequency 3",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_frequency_4": {
        "dp_id": 119,
        "code": "factory_default_frequency_4",
        "raw_source": "parameter_group_2",
        "field_index": 13,
        "encoding": "int32_be",
        "name": "Factory Default - Frequency 4",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_frequency_5": {
        "dp_id": 119,
        "code": "factory_default_frequency_5",
        "raw_source": "parameter_group_2",
        "field_index": 14,
        "encoding": "int32_be",
        "name": "Factory Default - Frequency 5",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_frequency_6": {
        "dp_id": 119,
        "code": "factory_default_frequency_6",
        "raw_source": "parameter_group_2",
        "field_index": 15,
        "encoding": "int32_be",
        "name": "Factory Default - Frequency 6",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_frequency_7": {
        "dp_id": 119,
        "code": "factory_default_frequency_7",
        "raw_source": "parameter_group_2",
        "field_index": 16,
        "encoding": "int32_be",
        "name": "Factory Default - Frequency 7",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_frequency_8": {
        "dp_id": 119,
        "code": "factory_default_frequency_8",
        "raw_source": "parameter_group_2",
        "field_index": 17,
        "encoding": "int32_be",
        "name": "Factory Default - Frequency 8",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_frequency_9": {
        "dp_id": 119,
        "code": "factory_default_frequency_9",
        "raw_source": "parameter_group_2",
        "field_index": 18,
        "encoding": "int32_be",
        "name": "Factory Default - Frequency 9",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_frequency_10": {
        "dp_id": 119,
        "code": "factory_default_frequency_10",
        "raw_source": "parameter_group_2",
        "field_index": 19,
        "encoding": "int32_be",
        "name": "Factory Default - Frequency 10",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_frequency_11": {
        "dp_id": 120,
        "code": "factory_default_frequency_11",
        "raw_source": "parameter_group_3",
        "field_index": 0,
        "encoding": "int32_be",
        "name": "Factory Default - Frequency 11",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_frequency_12": {
        "dp_id": 120,
        "code": "factory_default_frequency_12",
        "raw_source": "parameter_group_3",
        "field_index": 1,
        "encoding": "int32_be",
        "name": "Factory Default - Frequency 12",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_frequency_lower_limit": {
        "dp_id": 120,
        "code": "factory_default_frequency_lower_limit",
        "raw_source": "parameter_group_3",
        "field_index": 2,
        "encoding": "int32_be",
        "name": "Factory Default - Frequency Lower Limit",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_frequency_upper_limit": {
        "dp_id": 120,
        "code": "factory_default_frequency_upper_limit",
        "raw_source": "parameter_group_3",
        "field_index": 3,
        "encoding": "int32_be",
        "name": "Factory Default - Frequency Upper Limit",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_hot_water_frequency_compensation": {
        "dp_id": 120,
        "code": "factory_default_hot_water_frequency_compensation",
        "raw_source": "parameter_group_3",
        "field_index": 4,
        "encoding": "int32_be",
        "name": "Factory Default - Hot Water Frequency Compensation",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "exhaust_tp01": {
        "dp_id": 120,
        "code": "exhaust_tp01",
        "raw_source": "parameter_group_3",
        "field_index": 6,
        "encoding": "int32_be",
        "name": "Exhaust TP01",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "factory_default_frequency_lower_limit_01": {
        "dp_id": 120,
        "code": "factory_default_frequency_lower_limit_01",
        "raw_source": "parameter_group_3",
        "field_index": 7,
        "encoding": "int32_be",
        "name": "Factory Default - Frequency Lower Limit 01",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_frequency_lower_limit_02": {
        "dp_id": 120,
        "code": "factory_default_frequency_lower_limit_02",
        "raw_source": "parameter_group_3",
        "field_index": 8,
        "encoding": "int32_be",
        "name": "Factory Default - Frequency Lower Limit 02",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_frequency_lower_limit_03": {
        "dp_id": 120,
        "code": "factory_default_frequency_lower_limit_03",
        "raw_source": "parameter_group_3",
        "field_index": 9,
        "encoding": "int32_be",
        "name": "Factory Default - Frequency Lower Limit 03",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_frequency_lower_limit_04": {
        "dp_id": 120,
        "code": "factory_default_frequency_lower_limit_04",
        "raw_source": "parameter_group_3",
        "field_index": 10,
        "encoding": "int32_be",
        "name": "Factory Default - Frequency Lower Limit 04",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_frequency_upper_limit_01": {
        "dp_id": 120,
        "code": "factory_default_frequency_upper_limit_01",
        "raw_source": "parameter_group_3",
        "field_index": 11,
        "encoding": "int32_be",
        "name": "Factory Default - Frequency Upper Limit 01",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_frequency_upper_limit_02": {
        "dp_id": 120,
        "code": "factory_default_frequency_upper_limit_02",
        "raw_source": "parameter_group_3",
        "field_index": 12,
        "encoding": "int32_be",
        "name": "Factory Default - Frequency Upper Limit 02",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_frequency_upper_limit_03": {
        "dp_id": 120,
        "code": "factory_default_frequency_upper_limit_03",
        "raw_source": "parameter_group_3",
        "field_index": 13,
        "encoding": "int32_be",
        "name": "Factory Default - Frequency Upper Limit 03",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_frequency_upper_limit_04": {
        "dp_id": 120,
        "code": "factory_default_frequency_upper_limit_04",
        "raw_source": "parameter_group_3",
        "field_index": 14,
        "encoding": "int32_be",
        "name": "Factory Default - Frequency Upper Limit 04",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_power_mode_frequency_increase": {
        "dp_id": 120,
        "code": "factory_default_power_mode_frequency_increase",
        "raw_source": "parameter_group_3",
        "field_index": 15,
        "encoding": "int32_be",
        "name": "Factory Default - Power Mode Frequency Increase",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_silent_mode_maximum_frequency": {
        "dp_id": 120,
        "code": "factory_default_silent_mode_maximum_frequency",
        "raw_source": "parameter_group_3",
        "field_index": 16,
        "encoding": "int32_be",
        "name": "Factory Default - Silent Mode Maximum Frequency",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_power_mode_cooling_frequency_increase": {
        "dp_id": 120,
        "code": "factory_default_power_mode_cooling_frequency_increase",
        "raw_source": "parameter_group_3",
        "field_index": 17,
        "encoding": "int32_be",
        "name": "Factory Default - Power Mode Cooling Frequency Increase",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_silent_mode_cooling_maximum_frequency": {
        "dp_id": 120,
        "code": "factory_default_silent_mode_cooling_maximum_frequency",
        "raw_source": "parameter_group_3",
        "field_index": 18,
        "encoding": "int32_be",
        "name": "Factory Default - Silent Mode Cooling Maximum Frequency",
    },
    "factory_default_circulation_pump_adjustment_period": {
        "dp_id": 120,
        "code": "factory_default_circulation_pump_adjustment_period",
        "raw_source": "parameter_group_3",
        "field_index": 19,
        "encoding": "int32_be",
        "name": "Factory Default - Circulation Pump Adjustment Period",
        "unit": "sec",
    },
    "factory_default_max_circulation_pump_speed": {
        "dp_id": 121,
        "code": "factory_default_max_circulation_pump_speed",
        "raw_source": "parameter_group_4",
        "field_index": 0,
        "encoding": "int32_be",
        "name": "Factory Default - Max Circulation Pump Speed",
        "unit": "%",
        "icon": "mdi:percent",
    },
    "factory_default_min_circulation_pump_speed": {
        "dp_id": 121,
        "code": "factory_default_min_circulation_pump_speed",
        "raw_source": "parameter_group_4",
        "field_index": 1,
        "encoding": "int32_be",
        "name": "Factory Default - Min Circulation Pump Speed",
        "unit": "%",
        "icon": "mdi:percent",
    },
    "factory_default_circulation_pump_speed_adjustment": {
        "dp_id": 121,
        "code": "factory_default_circulation_pump_speed_adjustment",
        "raw_source": "parameter_group_4",
        "field_index": 2,
        "encoding": "int32_be",
        "name": "Factory Default - Circulation Pump Speed Adjustment",
        "unit": "%",
        "icon": "mdi:percent",
    },
    "factory_default_inlet_outlet_temperature_difference": {
        "dp_id": 121,
        "code": "factory_default_inlet_outlet_temperature_difference",
        "raw_source": "parameter_group_4",
        "field_index": 3,
        "encoding": "int32_be",
        "name": "Factory Default - Inlet/Outlet Temperature Difference",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "factory_default_expansion_valve_response_time": {
        "dp_id": 121,
        "code": "factory_default_expansion_valve_response_time",
        "raw_source": "parameter_group_4",
        "field_index": 4,
        "encoding": "int32_be",
        "name": "Factory Default - Expansion Valve Response Time",
        "unit": "sec",
    },
    "factory_default_power_mode_main_valve_temperature_1": {
        "dp_id": 121,
        "code": "factory_default_power_mode_main_valve_temperature_1",
        "raw_source": "parameter_group_4",
        "field_index": 5,
        "encoding": "int32_be",
        "name": "Factory Default - Power Mode Main Valve Temperature 1",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "factory_default_power_mode_main_valve_temperature_2": {
        "dp_id": 121,
        "code": "factory_default_power_mode_main_valve_temperature_2",
        "raw_source": "parameter_group_4",
        "field_index": 6,
        "encoding": "int32_be",
        "name": "Factory Default - Power Mode Main Valve Temperature 2",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "factory_default_power_mode_main_valve_temperature_3": {
        "dp_id": 121,
        "code": "factory_default_power_mode_main_valve_temperature_3",
        "raw_source": "parameter_group_4",
        "field_index": 7,
        "encoding": "int32_be",
        "name": "Factory Default - Power Mode Main Valve Temperature 3",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "factory_default_power_mode_main_valve_temperature_4": {
        "dp_id": 121,
        "code": "factory_default_power_mode_main_valve_temperature_4",
        "raw_source": "parameter_group_4",
        "field_index": 8,
        "encoding": "int32_be",
        "name": "Factory Default - Power Mode Main Valve Temperature 4",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "factory_default_power_mode_main_valve_temperature_5": {
        "dp_id": 121,
        "code": "factory_default_power_mode_main_valve_temperature_5",
        "raw_source": "parameter_group_4",
        "field_index": 9,
        "encoding": "int32_be",
        "name": "Factory Default - Power Mode Main Valve Temperature 5",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "factory_default_power_mode_main_valve_temperature_6": {
        "dp_id": 121,
        "code": "factory_default_power_mode_main_valve_temperature_6",
        "raw_source": "parameter_group_4",
        "field_index": 10,
        "encoding": "int32_be",
        "name": "Factory Default - Power Mode Main Valve Temperature 6",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "factory_default_power_mode_main_valve_temperature_7": {
        "dp_id": 121,
        "code": "factory_default_power_mode_main_valve_temperature_7",
        "raw_source": "parameter_group_4",
        "field_index": 11,
        "encoding": "int32_be",
        "name": "Factory Default - Power Mode Main Valve Temperature 7",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "factory_default_power_mode_main_valve_temperature_8": {
        "dp_id": 121,
        "code": "factory_default_power_mode_main_valve_temperature_8",
        "raw_source": "parameter_group_4",
        "field_index": 12,
        "encoding": "int32_be",
        "name": "Factory Default - Power Mode Main Valve Temperature 8",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "factory_default_power_mode_cooling_main_valve_temperature_1": {
        "dp_id": 121,
        "code": "factory_default_power_mode_cooling_main_valve_temperature_1",
        "raw_source": "parameter_group_4",
        "field_index": 13,
        "encoding": "int32_be",
        "name": "Factory Default - Power Mode Cooling Main Valve Temperature 1",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "factory_default_power_mode_cooling_main_valve_temperature_2": {
        "dp_id": 121,
        "code": "factory_default_power_mode_cooling_main_valve_temperature_2",
        "raw_source": "parameter_group_4",
        "field_index": 14,
        "encoding": "int32_be",
        "name": "Factory Default - Power Mode Cooling Main Valve Temperature 2",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_power_mode_cooling_main_valve_temperature_3": {
        "dp_id": 121,
        "code": "factory_default_power_mode_cooling_main_valve_temperature_3",
        "raw_source": "parameter_group_4",
        "field_index": 15,
        "encoding": "int32_be",
        "name": "Factory Default - Power Mode Cooling Main Valve Temperature 3",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_power_mode_cooling_main_valve_temperature_4": {
        "dp_id": 121,
        "code": "factory_default_power_mode_cooling_main_valve_temperature_4",
        "raw_source": "parameter_group_4",
        "field_index": 16,
        "encoding": "int32_be",
        "name": "Factory Default - Power Mode Cooling Main Valve Temperature 4",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "factory_default_max_fan_speed_silent_mode": {
        "dp_id": 124,
        "code": "factory_default_max_fan_speed_silent_mode",
        "raw_source": "parameter_group_7",
        "field_index": 3,
        "encoding": "int32_be",
        "name": "Factory Default - Max Fan Speed Silent Mode",
    },
    "factory_default_max_fan_speed_silent_mode_cooling": {
        "dp_id": 124,
        "code": "factory_default_max_fan_speed_silent_mode_cooling",
        "raw_source": "parameter_group_7",
        "field_index": 4,
        "encoding": "int32_be",
        "name": "Factory Default - Max Fan Speed Silent Mode (Cooling)",
    },
}

# ====================================================
# BINARY SENSOR TYPES (read-only bitmap - accessMode: "ro")
# ====================================================
BINARY_SENSOR_TYPES = {
    # Fault Status (dp_id: 15)
    "fault": {
        "dp_id": 15,
        "code": "fault",
        "name": "Fault Status",
        "device_class": "problem",
        "conversion": "value != 0",
    },
}

# ====================================================
# SWITCH TYPES (read-write bool - accessMode: "rw")
# ====================================================
SWITCH_TYPES = {
    # Power Switch (dp_id: 1)
    "switch": {
        "dp_id": 1,
        "code": "switch",
        "name": "Power",
        "icon": "mdi:power",
        "conversion": "value in [1, True, '1', 'true', 'on', 'yes', 'enable', 'open']",
    },
    # Reset to Default (dp_id: 125) - accessMode: "wr"
    "reset": {
        "dp_id": 125,
        "code": "reset",
        "name": "Reset to Default",
        "icon": "mdi:restore",
        "conversion": "value in [1, True, '1', 'true', 'on', 'yes', 'enable', 'open']",
    },
}

# ====================================================
# SELECT TYPES (read-write enum - accessMode: "rw")
# ====================================================
SELECT_TYPES = {
    # Operation Mode (dp_id: 2) - smart, strong, mute
    "mode": {
        "dp_id": 2,
        "code": "mode",
        "name": "Operation Mode",
        "icon": "mdi:hvac",
        "options": {
            "smart": "Smart",
            "strong": "Strong",
            "mute": "Mute",
        },
    },
    # Work Mode (dp_id: 5) - wth, heat, cool, wth_heat, wth_cool
    "work_mode": {
        "dp_id": 5,
        "code": "work_mode",
        "name": "Work Mode",
        "icon": "mdi:cog",
        "options": {
            "wth": "Hot Water",
            "heat": "Heating",
            "cool": "Cooling",
            "wth_heat": "Hot Water + Heating",
            "wth_cool": "Hot Water + Cooling",
        },
    },
    # Temperature Unit (dp_id: 6) - c, f
    "temp_unit_convert": {
        "dp_id": 6,
        "code": "temp_unit_convert",
        "name": "Temperature Unit",
        "icon": "mdi:thermometer",
        "options": {
            "c": "Celsius",
            "f": "Fahrenheit",
        },
    },
}
