"""Model mapping for Heat Pump (fc1fls)."""

MODEL_NAME = "Heat Pump (fc1fls)"
# ====================================================
# Power World R290 @brownnath2000
# ====================================================
SENSOR_TYPES = {
    # ========== FAULT & STATUS ==========
    "custom_fault_bit": {
        "dp_id": 199,
        "code": "custom_fault_bit",
        "name": "Custom Fault",
        "icon": "mdi:alert-circle",
        "device_class": "problem",
        "state_class": "measurement",
    },
    "products_id": {
        "dp_id": 180,
        "code": "products_id",
        "name": "Product ID",
        "icon": "mdi:identifier",
    },
}

# ====================================================
# BINARY SENSOR TYPES (read-only bool/bitmap - accessMode: "ro")
# ====================================================
BINARY_SENSOR_TYPES = {
    "fault": {
        "dp_id": 15,
        "code": "fault",
        "name": "Fault Alarm",
        "icon": "mdi:alert-circle",
        "device_class": "problem",
        "conversion": "value != 0"
    },
}

# ====================================================
# SWITCH TYPES (read-write bool - accessMode: "rw")
# ====================================================
SWITCH_TYPES = {
    "switch": {
        "dp_id": 1,
        "code": "switch",
        "name": "Power",
        "icon": "mdi:power",
        "conversion": "value in [1, True, '1', 'true', 'on', 'yes', 'enable', 'open']"
    },
    "reset": {
        "dp_id": 125,
        "code": "reset",
        "name": "Reset to Default",
        "icon": "mdi:restore",
        "conversion": "value in [1, True, '1', 'true', 'on', 'yes', 'enable', 'open']"
    },
}

# ====================================================
# NUMBER TYPES (read-write value - accessMode: "rw")
# ====================================================
NUMBER_TYPES = {
    "hot_water_set": {
        "dp_id": 110,
        "code": "hot_water_set",
        "name": "Hot Water Temperature Setpoint",
        "icon": "mdi:water-thermometer",
        "unit": "°C",
        "min_value": 0.0,
        "max_value": 99.0,
        "step": 1.0,
        "api_conversion": "value"
    },
    "heating_setting": {
        "dp_id": 111,
        "code": "heating_setting",
        "name": "Heating Temperature Setpoint",
        "icon": "mdi:thermostat",
        "unit": "°C",
        "min_value": 0.0,
        "max_value": 99.0,
        "step": 1.0,
        "api_conversion": "value"
    },
    "cooling_setting": {
        "dp_id": 112,
        "code": "cooling_setting",
        "name": "Cooling Temperature Setpoint",
        "icon": "mdi:snowflake",
        "unit": "°C",
        "min_value": 0.0,
        "max_value": 99.0,
        "step": 1.0,
        "api_conversion": "value"
    },
    "hdef": {
        "dp_id": 130,
        "code": "hdef",
        "name": "Force Defrost",
        "icon": "mdi:snowflake-melt",
        "unit": "",
        "min_value": 1.0,
        "max_value": 8.0,
        "step": 1.0,
        "api_conversion": "value"
    },
}

# ====================================================
# SELECT TYPES (read-write enum - accessMode: "rw")
# ====================================================
SELECT_TYPES = {
    "mode": {
        "dp_id": 2,
        "code": "mode",
        "name": "Frequency Mode",
        "icon": "mdi:sine-wave",
        "options": {
            "smart": "Smart",
            "strong": "Strong",
            "mute": "Mute"
        },
    },
    "work_mode": {
        "dp_id": 5,
        "code": "work_mode",
        "name": "Operation Mode",
        "icon": "mdi:hvac",
        "options": {
            "wth": "Hot Water",
            "heat": "Heating",
            "cool": "Cooling",
            "wth_heat": "Hot Water + Heating",
            "wth_cool": "Hot Water + Cooling"
        },
    },
    "temp_unit_convert": {
        "dp_id": 6,
        "code": "temp_unit_convert",
        "name": "Temperature Unit",
        "icon": "mdi:thermometer",
        "options": {
            "c": "Celsius",
            "f": "Fahrenheit"
        },
    },
}

# ====================================================
# RAW PAYLOAD DECODING (dp 101, 118, 119, 124, 140)
# Contributed by @brownnath2000 via raw_explorer.py (2026-08-30).
#
# The raw_explorer.py export placed several read-only telemetry fields
# from parameter_group_23 (dp 140) under NUMBER_TYPES even though their
# own field names ended in "_ro" (read-only) — corrected below and
# moved into SENSOR_TYPES. The device-clock fields (current_year/
# month/day/hour/minute/second, also dp 140) had the same mistake,
# fixed the same way. A misspelling in the original export
# ("tempurature") is also fixed here.
# ====================================================

# --- merge into SENSOR_TYPES (safe even if already defined above) ---
SENSOR_TYPES = globals().get("SENSOR_TYPES", {})
SENSOR_TYPES.update({
    # ---- status_parameter_group_1 (dp 101) — live system telemetry ----
    "water_inlet_temperature": {
        "dp_id": 101,
        "code": "water_inlet_temperature",
        "raw_source": "status_parameter_group_1",
        "field_index": 0,
        "encoding": "int32_be",
        "name": "Water Inlet Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer-water",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "water_outlet_temperature": {
        "dp_id": 101,
        "code": "water_outlet_temperature",
        "raw_source": "status_parameter_group_1",
        "field_index": 1,
        "encoding": "int32_be",
        "name": "Water Outlet Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer-water",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "ambient_temperature": {
        "dp_id": 101,
        "code": "ambient_temperature",
        "raw_source": "status_parameter_group_1",
        "field_index": 2,
        "encoding": "int32_be",
        "name": "Ambient Temperature",
        "unit": "°C",
        "icon": "mdi:home-thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "exhaust_gas_temperature": {
        "dp_id": 101,
        "code": "exhaust_gas_temperature",
        "raw_source": "status_parameter_group_1",
        "field_index": 3,
        "encoding": "int32_be",
        "name": "Exhaust Gas Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer-alert",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "return_gas_temperature": {
        "dp_id": 101,
        "code": "return_gas_temperature",
        "raw_source": "status_parameter_group_1",
        "field_index": 4,
        "encoding": "int32_be",
        "name": "Return Gas Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "evaporator_coil_temperature": {
        "dp_id": 101,
        "code": "evaporator_coil_temperature",
        "raw_source": "status_parameter_group_1",
        "field_index": 5,
        "encoding": "int32_be",
        "name": "Evaporator Coil Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer-lines",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "cooling_coil_temperature": {
        "dp_id": 101,
        "code": "cooling_coil_temperature",
        "raw_source": "status_parameter_group_1",
        "field_index": 6,
        "encoding": "int32_be",
        "name": "Cooling Coil Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer-lines",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "hot_water_cylinder_tank_temperature": {
        "dp_id": 101,
        "code": "hot_water_cylinder_tank_temperature",
        "raw_source": "status_parameter_group_1",
        "field_index": 7,
        "encoding": "int32_be",
        "name": "Hot Water Cylinder / Water Tank Temperature",
        "unit": "°C",
        "icon": "mdi:water-thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "main_expansion_valve_opening": {
        "dp_id": 101,
        "code": "main_expansion_valve_opening",
        "raw_source": "status_parameter_group_1",
        "field_index": 8,
        "encoding": "int32_be",
        "name": "Opening Steps of Main Expansion Valve",
        "unit": "P",
        "icon": "mdi:pipe-valve",
        "state_class": "measurement",
    },
    "assistant_expansion_valve_opening": {
        "dp_id": 101,
        "code": "assistant_expansion_valve_opening",
        "raw_source": "status_parameter_group_1",
        "field_index": 9,
        "encoding": "int32_be",
        "name": "Opening Steps of Assistant Expansion Valve",
        "unit": "P",
        "icon": "mdi:pipe-valve",
        "state_class": "measurement",
    },
    "compressor_current": {
        "dp_id": 101,
        "code": "compressor_current",
        "raw_source": "status_parameter_group_1",
        "field_index": 10,
        "encoding": "int32_be",
        "name": "Compressor Current",
        "unit": "A",
        "icon": "mdi:current-ac",
        "device_class": "current",
        "state_class": "measurement",
    },
    "heat_sink_temperature": {
        "dp_id": 101,
        "code": "heat_sink_temperature",
        "raw_source": "status_parameter_group_1",
        "field_index": 11,
        "encoding": "int32_be",
        "name": "Heat Sink Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "dc_bus_voltage": {
        "dp_id": 101,
        "code": "dc_bus_voltage",
        "raw_source": "status_parameter_group_1",
        "field_index": 12,
        "encoding": "int32_be",
        "name": "DC Bus Voltage",
        "unit": "V",
        "icon": "mdi:lightning-bolt",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    "compressor_actual_frequency": {
        "dp_id": 101,
        "code": "compressor_actual_frequency",
        "raw_source": "status_parameter_group_1",
        "field_index": 13,
        "encoding": "int32_be",
        "name": "Compressor Actual Frequency",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "dc_fan_1_speed": {
        "dp_id": 101,
        "code": "dc_fan_1_speed",
        "raw_source": "status_parameter_group_1",
        "field_index": 14,
        "encoding": "int32_be",
        "name": "Wind Speed of DC Fan 1",
        "unit": "rpm",
        "icon": "mdi:fan",
        "state_class": "measurement",
    },
    "dc_fan_2_speed": {
        "dp_id": 101,
        "code": "dc_fan_2_speed",
        "raw_source": "status_parameter_group_1",
        "field_index": 15,
        "encoding": "int32_be",
        "name": "Wind Speed of DC Fan 2 (Not on this model)",
        "unit": "rpm",
        "icon": "mdi:fan",
        "state_class": "measurement",
    },
    "low_pressure_sensor_value": {
        "dp_id": 101,
        "code": "low_pressure_sensor_value",
        "raw_source": "status_parameter_group_1",
        "field_index": 16,
        "encoding": "int32_be",
        "name": "Low Pressure Sensor Value",
        "unit": "bar",
        "icon": "mdi:gauge",
        "device_class": "pressure",
        "state_class": "measurement",
    },
    "low_pressure_conversion_temperature": {
        "dp_id": 101,
        "code": "low_pressure_conversion_temperature",
        "raw_source": "status_parameter_group_1",
        "field_index": 17,
        "encoding": "int32_be",
        "name": "Low Pressure Conversion Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "euv_powered_signal": {
        "dp_id": 101,
        "code": "euv_powered_signal",
        "raw_source": "status_parameter_group_1",
        "field_index": 18,
        "encoding": "int32_be",
        "name": "EUV Powered Signal",
        "icon": "mdi:electric-switch",
        "state_class": "measurement",
    },
    "sg_grid_signal": {
        "dp_id": 101,
        "code": "sg_grid_signal",
        "raw_source": "status_parameter_group_1",
        "field_index": 19,
        "encoding": "int32_be",
        "name": "SG Grid Signal",
        "icon": "mdi:transmission-tower",
        "state_class": "measurement",
    },

    # ---- parameter_group_23 (dp 140) — capacity, flow, power, energy ----
    # NOTE: these were misclassified as NUMBER_TYPES in the raw_explorer
    # export (their own field names end in "_ro" = read-only) — moved
    # here since they are live telemetry the device reports, not
    # settable values.
    "heating_cooling_capacity": {
        "dp_id": 140,
        "code": "heating_cooling_capacity",
        "raw_source": "parameter_group_23",
        "field_index": 0,
        "encoding": "int32_be",
        "conversion": "value / 100",
        "name": "Heating Capacity / Cooling Capacity",
        "unit": "kW",
        "icon": "mdi:heat-pump",
        "device_class": "power",
        "state_class": "measurement",
    },
    "current_water_flow_rate": {
        "dp_id": 140,
        "code": "current_water_flow_rate",
        "raw_source": "parameter_group_23",
        "field_index": 1,
        "encoding": "int32_be",
        "conversion": "value / 100",
        "name": "Current Water Flow Rate",
        "unit": "m³/h",
        "icon": "mdi:water-pump",
        "state_class": "measurement",
    },
    "voltage_of_entire_machine": {
        "dp_id": 140,
        "code": "voltage_of_entire_machine",
        "raw_source": "parameter_group_23",
        "field_index": 3,
        "encoding": "int32_be",
        "name": "Voltage of Entire Machine",
        "unit": "V",
        "icon": "mdi:lightning-bolt",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    "power_of_entire_machine": {
        "dp_id": 140,
        "code": "power_of_entire_machine",
        "raw_source": "parameter_group_23",
        "field_index": 4,
        "encoding": "int32_be",
        "name": "Power of Entire Machine",
        "unit": "W",
        "icon": "mdi:flash",
        "device_class": "power",
        "state_class": "measurement",
    },
    "cop_eer": {
        "dp_id": 140,
        "code": "cop_eer",
        "raw_source": "parameter_group_23",
        "field_index": 5,
        "encoding": "int32_be",
        "name": "COP (EER)",
        "icon": "mdi:chart-line",
        "state_class": "measurement",
    },
    "target_rotation_speed_of_dc_water_pump": {
        "dp_id": 140,
        "code": "target_rotation_speed_of_dc_water_pump",
        "raw_source": "parameter_group_23",
        "field_index": 6,
        "encoding": "int32_be",
        "name": "Target Rotation Speed of DC Water Pump",
        "unit": "%",
        "icon": "mdi:pump",
        "state_class": "measurement",
    },
    "actual_rotation_speed_of_dc_water_pump": {
        "dp_id": 140,
        "code": "actual_rotation_speed_of_dc_water_pump",
        "raw_source": "parameter_group_23",
        "field_index": 7,
        "encoding": "int32_be",
        "conversion": "value / 10",
        "name": "Actual Rotation Speed of DC Water Pump",
        "unit": "%",
        "icon": "mdi:pump",
        "state_class": "measurement",
    },
    "current_year": {
        "dp_id": 140,
        "code": "current_year",
        "raw_source": "parameter_group_23",
        "field_index": 11,
        "encoding": "int32_be",
        "name": "Current Year",
        "icon": "mdi:calendar",
    },
    "current_month": {
        "dp_id": 140,
        "code": "current_month",
        "raw_source": "parameter_group_23",
        "field_index": 12,
        "encoding": "int32_be",
        "name": "Current Month",
        "icon": "mdi:calendar-month",
    },
    "current_day": {
        "dp_id": 140,
        "code": "current_day",
        "raw_source": "parameter_group_23",
        "field_index": 13,
        "encoding": "int32_be",
        "name": "Current Day",
        "icon": "mdi:calendar-today",
    },
    "current_hour": {
        "dp_id": 140,
        "code": "current_hour",
        "raw_source": "parameter_group_23",
        "field_index": 14,
        "encoding": "int32_be",
        "name": "Current Hour (24H)",
        "icon": "mdi:clock-outline",
    },
    "current_minute": {
        "dp_id": 140,
        "code": "current_minute",
        "raw_source": "parameter_group_23",
        "field_index": 15,
        "encoding": "int32_be",
        "name": "Current Minute",
        "icon": "mdi:clock-outline",
    },
    "current_second": {
        "dp_id": 140,
        "code": "current_second",
        "raw_source": "parameter_group_23",
        "field_index": 16,
        "encoding": "int32_be",
        "name": "Current Second",
        "icon": "mdi:clock-outline",
    },
})

# --- merge into NUMBER_TYPES (safe even if already defined above) ---
NUMBER_TYPES = globals().get("NUMBER_TYPES", {})
NUMBER_TYPES.update({
    # ---- parameter_group_1 (dp 118) — writable setpoints/settings ----
    "temp_diff_return_water_vs_cooling_heating_target": {
        "dp_id": 118,
        "code": "temp_diff_return_water_vs_cooling_heating_target",
        "raw_source": "parameter_group_1",
        "field_index": 0,
        "encoding": "int32_be",
        "step": 1.0,
        "api_conversion": "value",
        "name": "Temp Diff of Return Water and (Cooling / Heating) Target Temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
    },
    "temp_diff_return_water_vs_dhw_target": {
        "dp_id": 118,
        "code": "temp_diff_return_water_vs_dhw_target",
        "raw_source": "parameter_group_1",
        "field_index": 1,
        "encoding": "int32_be",
        "step": 1.0,
        "api_conversion": "value",
        "name": "Temp Diff of Return Water and (DHW) Target Temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
    },
    "target_hot_water_temperature_dhw": {
        "dp_id": 118,
        "code": "target_hot_water_temperature_dhw",
        "raw_source": "parameter_group_1",
        "field_index": 2,
        "encoding": "int32_be",
        "step": 1.0,
        "api_conversion": "value",
        "name": "Target Hot Water Temperature (DHW)",
        "unit": "°C",
        "icon": "mdi:water-thermometer",
    },
    "cooling_target_temperature": {
        "dp_id": 118,
        "code": "cooling_target_temperature",
        "raw_source": "parameter_group_1",
        "field_index": 3,
        "encoding": "int32_be",
        "step": 1.0,
        "api_conversion": "value",
        "name": "Cooling Target Temperature",
        "unit": "°C",
        "icon": "mdi:snowflake-thermometer",
    },
    "heating_target_temperature": {
        "dp_id": 118,
        "code": "heating_target_temperature",
        "raw_source": "parameter_group_1",
        "field_index": 4,
        "encoding": "int32_be",
        "step": 1.0,
        "api_conversion": "value",
        "name": "Heating Target Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer-lines",
    },
    "water_temp_compensation": {
        "dp_id": 118,
        "code": "water_temp_compensation",
        "raw_source": "parameter_group_1",
        "field_index": 5,
        "encoding": "int32_be",
        "step": 1.0,
        "api_conversion": "value",
        "name": "Water Temp Compensation",
        "unit": "°C",
        "icon": "mdi:thermometer",
    },
    "high_temp_disinfection_cycle_days": {
        "dp_id": 118,
        "code": "high_temp_disinfection_cycle_days",
        "raw_source": "parameter_group_1",
        "field_index": 6,
        "encoding": "int32_be",
        "step": 1.0,
        "api_conversion": "value",
        "name": "High Temp Disinfection Cycle Days (0 is off)",
        "unit": "d",
        "icon": "mdi:calendar-sync",
    },
    "high_temp_disinfection_start_time": {
        "dp_id": 118,
        "code": "high_temp_disinfection_start_time",
        "raw_source": "parameter_group_1",
        "field_index": 7,
        "encoding": "int32_be",
        "step": 1.0,
        "api_conversion": "value",
        "name": "High Temp Disinfection Start Time (24H clock)",
        "unit": "h",
        "icon": "mdi:clock-start",
    },
    "high_temp_disinfection_sustaining_time": {
        "dp_id": 118,
        "code": "high_temp_disinfection_sustaining_time",
        "raw_source": "parameter_group_1",
        "field_index": 8,
        "encoding": "int32_be",
        "step": 1.0,
        "api_conversion": "value",
        "name": "High Temp Disinfection Sustaining Time",
        "unit": "min",
        "icon": "mdi:clock-outline",
    },
    "high_temp_disinfection_setting_temp": {
        "dp_id": 118,
        "code": "high_temp_disinfection_setting_temp",
        "raw_source": "parameter_group_1",
        "field_index": 9,
        "encoding": "int32_be",
        "step": 1.0,
        "api_conversion": "value",
        "name": "High Temp Disinfection Setting Temp",
        "unit": "°C",
        "icon": "mdi:thermometer-high",
    },
    "heat_pump_setting_temp_for_high_temp_disinfection": {
        "dp_id": 118,
        "code": "heat_pump_setting_temp_for_high_temp_disinfection",
        "raw_source": "parameter_group_1",
        "field_index": 10,
        "encoding": "int32_be",
        "step": 1.0,
        "api_conversion": "value",
        "name": "Heat Pump Setting Temp for High Temp Disinfection",
        "unit": "°C",
        "icon": "mdi:thermometer-high",
    },
    "heating_compensation_temp_point_ambient": {
        "dp_id": 118,
        "code": "heating_compensation_temp_point_ambient",
        "raw_source": "parameter_group_1",
        "field_index": 12,
        "encoding": "int32_be",
        "step": 1.0,
        "api_conversion": "value",
        "name": "Heating Compensation Temp Point (Ambient)",
        "unit": "°C",
        "icon": "mdi:thermometer",
    },
    "target_temp_compensation_coefficient_heating_curve": {
        "dp_id": 118,
        "code": "target_temp_compensation_coefficient_heating_curve",
        "raw_source": "parameter_group_1",
        "field_index": 13,
        "encoding": "int32_be",
        "step": 1.0,
        "api_conversion": "value",
        "name": "Target Temp Compensation Coefficient (Heating Curve)",
        "icon": "mdi:tune",
    },
    "ambient_temp_set_point_for_starting_auxiliary_heating": {
        "dp_id": 118,
        "code": "ambient_temp_set_point_for_starting_auxiliary_heating",
        "raw_source": "parameter_group_1",
        "field_index": 15,
        "encoding": "int32_be",
        "step": 1.0,
        "api_conversion": "value",
        "name": "Ambient Temp Set Point for Starting Auxiliary Heating",
        "unit": "°C",
        "icon": "mdi:thermometer",
    },
    "aux_heater_start_delay_for_water_tank": {
        "dp_id": 118,
        "code": "aux_heater_start_delay_for_water_tank",
        "raw_source": "parameter_group_1",
        "field_index": 16,
        "encoding": "int32_be",
        "step": 1.0,
        "api_conversion": "value",
        "name": "Start Time (Delay) for Electric Heating of Water Tank",
        "icon": "mdi:clock-start",
    },
    "circulation_pump_intermittent_interval": {
        "dp_id": 118,
        "code": "circulation_pump_intermittent_interval",
        "raw_source": "parameter_group_1",
        "field_index": 19,
        "encoding": "int32_be",
        "step": 1.0,
        "api_conversion": "value",
        "name": "Circulation Pump Intermittent Interval",
        "unit": "min",
        "icon": "mdi:pump",
    },

    # ---- parameter_group_2 (dp 119) ----
    "dc_water_pump_manual_speed": {
        "dp_id": 119,
        "code": "dc_water_pump_manual_speed",
        "raw_source": "parameter_group_2",
        "field_index": 1,
        "encoding": "int32_be",
        "step": 1.0,
        "api_conversion": "value",
        "name": "DC Water Pump Manual Speed",
        "unit": "%",
        "icon": "mdi:pump",
    },

    # ---- parameter_group_7 (dp 124) ----
    "smart_grid_operation_time": {
        "dp_id": 124,
        "code": "smart_grid_operation_time",
        "raw_source": "parameter_group_7",
        "field_index": 13,
        "encoding": "int32_be",
        "step": 1.0,
        "api_conversion": "value",
        "name": "Smart Grid Operation Time",
        "unit": "min",
        "icon": "mdi:timer-outline",
    },
})

# --- merge into SELECT_TYPES (safe even if already defined above) ---
SELECT_TYPES = globals().get("SELECT_TYPES", {})
SELECT_TYPES.update({
    "heating_target_temp_auto_adjustment": {
        "dp_id": 118,
        "code": "heating_target_temp_auto_adjustment",
        "raw_source": "parameter_group_1",
        "field_index": 11,
        "encoding": "int32_be",
        "options": {
            "0": "Forbidden",
            "1": "Resume",
        },
        "name": "Heating Target Temp Automatic Adjustment",
        "icon": "mdi:thermostat-auto",
    },
    "frequency_operating_mode_after_constant_temp": {
        "dp_id": 118,
        "code": "frequency_operating_mode_after_constant_temp",
        "raw_source": "parameter_group_1",
        "field_index": 14,
        "encoding": "int32_be",
        "options": {
            "0": "Decreased Frequency",
            "1": "Non-decreased Frequency",
        },
        "name": "Frequency Operating Mode after Constant Temp",
        "icon": "mdi:sine-wave",
    },
    "heat_pump_function": {
        "dp_id": 118,
        "code": "heat_pump_function",
        "raw_source": "parameter_group_1",
        "field_index": 17,
        "encoding": "int32_be",
        "options": {
            "1": "Heating only",
            "2": "Heating and Cooling",
            "3": "Heating and DHW",
            "4": "Heating, Cooling and DHW",
        },
        "name": "Heat Pump Function",
        "icon": "mdi:heat-pump",
    },
    "circulation_pump_status_after_reaching_target_temp": {
        "dp_id": 118,
        "code": "circulation_pump_status_after_reaching_target_temp",
        "raw_source": "parameter_group_1",
        "field_index": 18,
        "encoding": "int32_be",
        "options": {
            "0": "Run intermittently",
            "1": "Run always",
            "2": "Stop",
        },
        "name": "Circulation Pump Status after Reaching Target Temp",
        "icon": "mdi:pump",
    },
    "dc_circulation_pump_mode": {
        "dp_id": 119,
        "code": "dc_circulation_pump_mode",
        "raw_source": "parameter_group_2",
        "field_index": 0,
        "encoding": "int32_be",
        "options": {
            "0": "Off",
            "1": "Auto",
            "2": "Manual",
        },
        "name": "DC Circulation Pump Mode",
        "icon": "mdi:pump",
    },
    "smart_grid_enable": {
        "dp_id": 124,
        "code": "smart_grid_enable",
        "raw_source": "parameter_group_7",
        "field_index": 12,
        "encoding": "int32_be",
        "options": {
            "0": "Forbidden",
            "1": "Resume",
        },
        "name": "Smart Grid Enable",
        "icon": "mdi:transmission-tower",
    },
})
