"""Model mapping for Klimalife Heat Pump (fru9b0)."""

MODEL_NAME = "Klimalife Heat Pump (fru9b0)"
# ====================================================
# Klimalife Heat Pump @jagoman81 (issue #98)
# Small local-manufacturer unit built on Elechico CC902 electronics/
# inverter driver. DP map sourced from raw_explorer.py, cross-checked
# with node-red and the Tuya app.
#
# temp_current (dp 16) and temp_current_f (dp 35) read -30 / -22
# sentinel values on this device (no probe wired to that DP) -- the
# real live temperatures live inside status_parameter_group_1/2
# (dp 101/127), decoded below as int32 fields, per Tuya's own
# "maxlen 128, raw" schema note ("this DP holds 20 parameters, 4
# bytes each").
#
# work_mode (dp 5) selects which of the three memorized setpoints
# (dp 110/111/112, exposed below as heating_setting/cooling_setting/
# hot_water_setting) is active; temp_set (dp 4) mirrors whichever one
# is currently selected, so changing it changes the setpoint for the
# CURRENT mode only -- change the per-mode numbers directly instead if
# you want to set a mode's target while it's not active.
#
# parameter_group_1..6 (dp 118-123) are the installer/engineer menu,
# password-protected on the device's own screen -- exposed here as
# plain numbers with no password, so change them only if you know
# what they do (contributor's own warning). A number of fields in
# here are still genuinely unidentified (named *_field_<n> below,
# "not documented yet") and a few pairs look like duplicated/near-
# duplicate values at two different offsets in the same block
# (suffixed "_2" below) -- kept rather than dropped since we can't
# tell which of a pair is the real one without further testing.
#
# fault (dp 15) is a 30-bit bitmap. Its own typeSpec "label" list is
# in internal/manufacturing order, NOT the same as the alarm numbers
# printed on the unit's display or in the factory manual (confirmed
# against the contributor's error-codes list) -- e.g. bitmap position
# 3 is labelled "E06" internally but shows as "Alarm E03" on the unit.
# Reference table (bit position -> display code -> meaning), for
# anyone decoding the bitmap value by hand:
#   bit  0  E00  -> E00      communication malfunction
#   bit  1  E01  -> E01      water inlet temperature sensor malfunction
#   bit  2  E02  -> E02      water outlet temperature sensor malfunction
#   bit  3  E06  -> E03      water flow switch protection
#   bit  4  E04  -> E04      power supply phase malfunction
#   bit  5  E05  -> E05      excessively big difference of water in/out temperature
#   bit  6  E07  -> E07      excessively high temperature of evaporator
#   bit  7  E08  -> E08      DHW water tank sensor malfunction
#   bit  8  E09  -> E09      air conditioner water tank sensor malfunction
#   bit  9  E10  -> E010     high pressure protection
#   bit 10  E11  -> E011     low pressure protection
#   bit 11  E12  -> E012     water outlet temperature excessively high
#   bit 12  E13  -> E013     water outlet temperature excessively low
#   bit 13  E14  -> E014     suction sensor malfunction
#   bit 14  E16  -> E016     discharge excessively high protection
#   bit 15  E19  -> E018/19  DHW/air conditioner two-class antifreezing
#   bit 16  E18  -> E018/19  DHW/air conditioner two-class antifreezing
#   bit 17  E20  -> E020     ambient temperature sensor malfunction
#   bit 18  E21  -> E021     heating evaporator temperature sensor malfunction
#   bit 19  E22  -> E022     cooling evaporator temperature sensor malfunction
#   bit 20  E23  -> E023     ambient temperature excessively high protection
#   bit 21  E31  -> E031     ambient temperature excessively low protection
#   bit 22  E33  -> E033     EVI entrance temperature malfunction
#   bit 23  E34  -> E034     EVI exit temperature malfunction
#   bit 24  E35  -> E035     solar energy temperature malfunction
#   bit 25  E27  -> E027     compressor over current protection
#   bit 26  E24  -> E024     module communication malfunction
#   bit 27  E37  -> E037     DC fan 1 malfunction
#   bit 28  E38  -> E038     DC fan 2 malfunction
#   bit 29  E15  -> E015     discharge sensor malfunction
# ====================================================

SENSOR_TYPES = {}

BINARY_SENSOR_TYPES = {
    "fault": {
        "dp_id": 15,
        "code": "fault",
        "name": "Fault Alarm",
        "device_class": "problem",
        "conversion": "value != 0",
    },
    "custom_fault_bit": {
        "dp_id": 199,
        "code": "custom_fault_bit",
        "name": "Inverter Module Fault",
        "device_class": "problem",
        "conversion": "value != 0",
    },
}

SWITCH_TYPES = {
    "switch": {
        "dp_id": 1,
        "code": "switch",
        "name": "Power",
        "icon": "mdi:power",
        "conversion": "value in [1, True, '1', 'true', 'on', 'yes', 'enable', 'open']",
    },
}

NUMBER_TYPES = {
    "temp_set": {
        "dp_id": 4,
        "code": "temp_set",
        "name": "Target Temperature",
        "icon": "mdi:thermometer",
        "unit": "\u00b0C",
        "min_value": 10.0,
        "max_value": 75.0,
        "step": 1.0,
        "api_conversion": "value",
    },
    "hot_water_setting": {
        "dp_id": 110,
        "code": "hot_water_setting",
        "name": "DHW Target Temperature",
        "icon": "mdi:water-thermometer",
        "unit": "\u00b0C",
        "min_value": 0.0,
        "max_value": 99.0,
        "step": 1.0,
        "api_conversion": "value",
    },
    "heating_setting": {
        "dp_id": 111,
        "code": "heating_setting",
        "name": "Heating Target Temperature",
        "icon": "mdi:thermometer-plus",
        "unit": "\u00b0C",
        "min_value": 0.0,
        "max_value": 99.0,
        "step": 1.0,
        "api_conversion": "value",
    },
    "cooling_setting": {
        "dp_id": 112,
        "code": "cooling_setting",
        "name": "Cooling Target Temperature",
        "icon": "mdi:thermometer-minus",
        "unit": "\u00b0C",
        "min_value": 0.0,
        "max_value": 99.0,
        "step": 1.0,
        "api_conversion": "value",
    },
}

SELECT_TYPES = {
    "work_mode": {
        "dp_id": 5,
        "code": "work_mode",
        "name": "Work Mode",
        "icon": "mdi:hvac",
        "options": {
            "heat": "Heating",
            "cool": "Cooling",
            "wth": "DHW",
            "wth_cool": "DHW + Cooling",
            "wth_heat": "DHW + Heating",
        },
    },
}

"""Raw-field entries generated by raw_explorer.py
Device: bf9d0bf765e118b73fsviu
Generated: 2026-10-06 18:01:45

Paste this whole file at the BOTTOM of the device model file, as-is.
Each block below merges into the matching dict (SENSOR_TYPES,
SWITCH_TYPES, NUMBER_TYPES, SELECT_TYPES, TEXT_TYPES) via .update(),
so it adds to whatever is already defined earlier in the file —
it will NOT wipe out existing entries, even if that dict name is
already used for plain (non-raw) DPs elsewhere in the same file.
The integration reads `raw_source` + `field_index` to decode/encode
the value from a raw payload rather than a plain DP.
"""

# --- merge into SENSOR_TYPES (safe even if already defined above) ---
SENSOR_TYPES = globals().get("SENSOR_TYPES", {})
SENSOR_TYPES.update({
    "dhw_actual_temperature": {
        "dp_id": 101,
        "code": "dhw_actual_temperature",
        "raw_source": "status_parameter_group_1",
        "field_index": 0,
        "encoding": "int32_be",
        "name": "DHW Actual Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "btw_actual_temperature": {
        "dp_id": 101,
        "code": "btw_actual_temperature",
        "raw_source": "status_parameter_group_1",
        "field_index": 1,
        "encoding": "int32_be",
        "conversion": "value / 10",
        "name": "BTW Actual Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "water_inlet_to_heatpump": {
        "dp_id": 101,
        "code": "water_inlet_to_heatpump",
        "raw_source": "status_parameter_group_1",
        "field_index": 2,
        "encoding": "int32_be",
        "name": "Water inlet to HeatPump",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "water_outlet_from_heatpump": {
        "dp_id": 101,
        "code": "water_outlet_from_heatpump",
        "raw_source": "status_parameter_group_1",
        "field_index": 3,
        "encoding": "int32_be",
        "name": "Water outlet from HeatPump",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "evaporator_inlet_gas_temp": {
        "dp_id": 101,
        "code": "evaporator_inlet_gas_temp",
        "raw_source": "status_parameter_group_1",
        "field_index": 4,
        "encoding": "int32_be",
        "name": "Evaporator Inlet Gas Temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "condenser_out_gas_temp": {
        "dp_id": 101,
        "code": "condenser_out_gas_temp",
        "raw_source": "status_parameter_group_1",
        "field_index": 5,
        "encoding": "int32_be",
        "name": "Condenser Out Gas Temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "condenser_in_gas_temp": {
        "dp_id": 101,
        "code": "condenser_in_gas_temp",
        "raw_source": "status_parameter_group_1",
        "field_index": 6,
        "encoding": "int32_be",
        "name": "Condenser In Gas Temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "evaporator_outlet_gas_temp": {
        "dp_id": 101,
        "code": "evaporator_outlet_gas_temp",
        "raw_source": "status_parameter_group_1",
        "field_index": 7,
        "encoding": "int32_be",
        "name": "Evaporator Outlet Gas Temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "ambient_temperature": {
        "dp_id": 101,
        "code": "ambient_temperature",
        "raw_source": "status_parameter_group_1",
        "field_index": 8,
        "encoding": "int32_be",
        "name": "Ambient Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "eev_opening": {
        "dp_id": 101,
        "code": "eev_opening",
        "raw_source": "status_parameter_group_1",
        "field_index": 9,
        "encoding": "int32_be",
        "name": "EEV Opening",
        "unit": "step",
        "icon": "mdi:pipe-valve",
    },
    "evi_inlet_temp": {
        "dp_id": 101,
        "code": "evi_inlet_temp",
        "raw_source": "status_parameter_group_1",
        "field_index": 10,
        "encoding": "int32_be",
        "name": "EVI Inlet Temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "solar_water_temp": {
        "dp_id": 101,
        "code": "solar_water_temp",
        "raw_source": "status_parameter_group_1",
        "field_index": 11,
        "encoding": "int32_be",
        "name": "Solar Water temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "inverter_ipm_temp": {
        "dp_id": 101,
        "code": "inverter_ipm_temp",
        "raw_source": "status_parameter_group_1",
        "field_index": 12,
        "encoding": "int32_be",
        "name": "Inverter IPM Temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "compressor_frequency": {
        "dp_id": 101,
        "code": "compressor_frequency",
        "raw_source": "status_parameter_group_1",
        "field_index": 13,
        "encoding": "int32_be",
        "name": "Compressor Frequency",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "compressor_current": {
        "dp_id": 101,
        "code": "compressor_current",
        "raw_source": "status_parameter_group_1",
        "field_index": 14,
        "encoding": "int32_be",
        "name": "Compressor Current",
        "unit": "A",
        "icon": "mdi:current-ac",
        "device_class": "current",
        "state_class": "measurement",
    },
    "compressor_type_code": {
        "dp_id": 101,
        "code": "compressor_type_code",
        "raw_source": "status_parameter_group_1",
        "field_index": 15,
        "encoding": "int32_be",
        "name": "Compressor Type Code",
    },
    "evi_outlet_temp": {
        "dp_id": 101,
        "code": "evi_outlet_temp",
        "raw_source": "status_parameter_group_1",
        "field_index": 16,
        "encoding": "int32_be",
        "name": "EVI Outlet Temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "evi_opening": {
        "dp_id": 101,
        "code": "evi_opening",
        "raw_source": "status_parameter_group_1",
        "field_index": 17,
        "encoding": "int32_be",
        "name": "EVI Opening",
        "unit": "step",
        "icon": "mdi:pipe-valve",
    },
    "inverter_dc_voltage": {
        "dp_id": 101,
        "code": "inverter_dc_voltage",
        "raw_source": "status_parameter_group_1",
        "field_index": 18,
        "encoding": "int32_be",
        "name": "Inverter DC Voltage",
        "unit": "V",
        "icon": "mdi:lightning-bolt",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    "fan_1_speed": {
        "dp_id": 101,
        "code": "fan_1_speed",
        "raw_source": "status_parameter_group_1",
        "field_index": 19,
        "encoding": "int32_be",
        "name": "Fan 1 Speed",
        "unit": "rpm",
        "icon": "mdi:fan",
    },
    "fan2_speed": {
        "dp_id": 127,
        "code": "fan2_speed",
        "raw_source": "status_parameter_group_2",
        "field_index": 0,
        "encoding": "int32_be",
        "name": "Fan2 speed",
        "unit": "rpm",
        "icon": "mdi:fan",
    },
    "low_side_pressure": {
        "dp_id": 127,
        "code": "low_side_pressure",
        "raw_source": "status_parameter_group_2",
        "field_index": 1,
        "encoding": "int32_be",
        "name": "Low side pressure",
        "unit": "bar",
    },
    "high_side_pressure": {
        "dp_id": 127,
        "code": "high_side_pressure",
        "raw_source": "status_parameter_group_2",
        "field_index": 2,
        "encoding": "int32_be",
        "name": "High side pressure",
        "unit": "bar",
    },
    "low_side_temp": {
        "dp_id": 127,
        "code": "low_side_temp",
        "raw_source": "status_parameter_group_2",
        "field_index": 3,
        "encoding": "int32_be",
        "name": "Low side temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "high_side_temp": {
        "dp_id": 127,
        "code": "high_side_temp",
        "raw_source": "status_parameter_group_2",
        "field_index": 4,
        "encoding": "int32_be",
        "name": "High side temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "ground_source_inlet_temp": {
        "dp_id": 127,
        "code": "ground_source_inlet_temp",
        "raw_source": "status_parameter_group_2",
        "field_index": 5,
        "encoding": "int32_be",
        "name": "Ground source inlet temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "ground_source_outlet_temp": {
        "dp_id": 127,
        "code": "ground_source_outlet_temp",
        "raw_source": "status_parameter_group_2",
        "field_index": 6,
        "encoding": "int32_be",
        "name": "Ground Source outlet temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "pump_operation_time": {
        "dp_id": 127,
        "code": "pump_operation_time",
        "raw_source": "status_parameter_group_2",
        "field_index": 7,
        "encoding": "int32_be",
        "name": "Pump operation time",
        "unit": "H",
    },
    "compressor_operation_time": {
        "dp_id": 127,
        "code": "compressor_operation_time",
        "raw_source": "status_parameter_group_2",
        "field_index": 8,
        "encoding": "int32_be",
        "name": "Compressor operation time",
        "unit": "H",
    },
    "btw_add1_operation_time": {
        "dp_id": 127,
        "code": "btw_add1_operation_time",
        "raw_source": "status_parameter_group_2",
        "field_index": 9,
        "encoding": "int32_be",
        "name": "BTW add1 operation time",
        "unit": "H",
    },
    "btw_add2_operation_time": {
        "dp_id": 127,
        "code": "btw_add2_operation_time",
        "raw_source": "status_parameter_group_2",
        "field_index": 10,
        "encoding": "int32_be",
        "name": "BTW add2 operation time",
        "unit": "H",
    },
    "dhw_add_operation_time": {
        "dp_id": 127,
        "code": "dhw_add_operation_time",
        "raw_source": "status_parameter_group_2",
        "field_index": 11,
        "encoding": "int32_be",
        "name": "DHW add operation time",
        "unit": "H",
    },
    "pump_operation_time_2": {
        "dp_id": 127,
        "code": "pump_operation_time_2",
        "raw_source": "status_parameter_group_2",
        "field_index": 12,
        "encoding": "int32_be",
        "name": "Pump operation time (2)",
        "unit": "H",
    },
    "compressor_operation_time_2": {
        "dp_id": 127,
        "code": "compressor_operation_time_2",
        "raw_source": "status_parameter_group_2",
        "field_index": 13,
        "encoding": "int32_be",
        "name": "Compressor operation time (2)",
        "unit": "H",
    },
    "btw_add1_operation_time_2": {
        "dp_id": 127,
        "code": "btw_add1_operation_time_2",
        "raw_source": "status_parameter_group_2",
        "field_index": 14,
        "encoding": "int32_be",
        "name": "BTW add1 operation time (2)",
        "unit": "H",
    },
    "btw_add2_operation_time_2": {
        "dp_id": 127,
        "code": "btw_add2_operation_time_2",
        "raw_source": "status_parameter_group_2",
        "field_index": 15,
        "encoding": "int32_be",
        "name": "BTW add2 operation time (2)",
        "unit": "H",
    },
    "dhw_add_operation_time_2": {
        "dp_id": 127,
        "code": "dhw_add_operation_time_2",
        "raw_source": "status_parameter_group_2",
        "field_index": 16,
        "encoding": "int32_be",
        "name": "DHW add operation time (2)",
        "unit": "H",
    },
    "dxpump_operation_time": {
        "dp_id": 127,
        "code": "dxpump_operation_time",
        "raw_source": "status_parameter_group_2",
        "field_index": 17,
        "encoding": "int32_be",
        "name": "DXpump operation time",
        "unit": "H",
    },
    "dxpump_operation_time_2": {
        "dp_id": 127,
        "code": "dxpump_operation_time_2",
        "raw_source": "status_parameter_group_2",
        "field_index": 18,
        "encoding": "int32_be",
        "name": "DXpump operation time (2)",
        "unit": "H",
    },
    "water_flow_status": {
        "dp_id": 127,
        "code": "water_flow_status",
        "raw_source": "status_parameter_group_2",
        "field_index": 19,
        "encoding": "int32_be",
        "name": "Water flow status?",
    },
    "etest_test_fr1": {
        "dp_id": 128,
        "code": "etest_test_fr1",
        "raw_source": "test_parameter_group",
        "field_index": 0,
        "encoding": "int32_be",
        "name": "(E-Test) Test Fr.1",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "etest_test_fr2": {
        "dp_id": 128,
        "code": "etest_test_fr2",
        "raw_source": "test_parameter_group",
        "field_index": 1,
        "encoding": "int32_be",
        "name": "(E-Test) Test Fr.2",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "etest_test_fr3": {
        "dp_id": 128,
        "code": "etest_test_fr3",
        "raw_source": "test_parameter_group",
        "field_index": 2,
        "encoding": "int32_be",
        "name": "(E-Test) Test Fr.3",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "etest_test_fr4": {
        "dp_id": 128,
        "code": "etest_test_fr4",
        "raw_source": "test_parameter_group",
        "field_index": 3,
        "encoding": "int32_be",
        "name": "(E-Test) Test Fr.4",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "etest_test_fr5": {
        "dp_id": 128,
        "code": "etest_test_fr5",
        "raw_source": "test_parameter_group",
        "field_index": 4,
        "encoding": "int32_be",
        "name": "(E-Test) Test Fr.5",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "etest_test_fr6": {
        "dp_id": 128,
        "code": "etest_test_fr6",
        "raw_source": "test_parameter_group",
        "field_index": 5,
        "encoding": "int32_be",
        "name": "(E-Test) Test Fr.6",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "etest_test_eev_step1": {
        "dp_id": 128,
        "code": "etest_test_eev_step1",
        "raw_source": "test_parameter_group",
        "field_index": 6,
        "encoding": "int32_be",
        "name": "(E-Test) Test EEV step1",
        "unit": "step",
        "icon": "mdi:pipe-valve",
    },
    "etest_test_eev_step2": {
        "dp_id": 128,
        "code": "etest_test_eev_step2",
        "raw_source": "test_parameter_group",
        "field_index": 7,
        "encoding": "int32_be",
        "name": "(E-Test) Test EEV step2",
        "unit": "step",
        "icon": "mdi:pipe-valve",
    },
    "etest_test_eev_step3": {
        "dp_id": 128,
        "code": "etest_test_eev_step3",
        "raw_source": "test_parameter_group",
        "field_index": 8,
        "encoding": "int32_be",
        "name": "(E-Test) Test EEV step3",
        "unit": "step",
        "icon": "mdi:pipe-valve",
    },
    "etest_test_eev_step4": {
        "dp_id": 128,
        "code": "etest_test_eev_step4",
        "raw_source": "test_parameter_group",
        "field_index": 9,
        "encoding": "int32_be",
        "name": "(E-Test) Test EEV step4",
        "unit": "step",
        "icon": "mdi:pipe-valve",
    },
    "etest_test_eev_step5": {
        "dp_id": 128,
        "code": "etest_test_eev_step5",
        "raw_source": "test_parameter_group",
        "field_index": 10,
        "encoding": "int32_be",
        "name": "(E-Test) Test EEV step5",
        "unit": "step",
        "icon": "mdi:pipe-valve",
    },
    "test_param_field_11": {
        "dp_id": 128,
        "code": "test_param_field_11",
        "raw_source": "test_parameter_group",
        "field_index": 11,
        "encoding": "int32_be",
        "name": "Test Parameter Group - field 11 (not documented yet)",
    },
    "test_param_field_12": {
        "dp_id": 128,
        "code": "test_param_field_12",
        "raw_source": "test_parameter_group",
        "field_index": 12,
        "encoding": "int32_be",
        "name": "Test Parameter Group - field 12 (not documented yet)",
    },
    "test_param_field_13": {
        "dp_id": 128,
        "code": "test_param_field_13",
        "raw_source": "test_parameter_group",
        "field_index": 13,
        "encoding": "int32_be",
        "name": "Test Parameter Group - field 13 (not documented yet)",
    },
    "test_param_field_14": {
        "dp_id": 128,
        "code": "test_param_field_14",
        "raw_source": "test_parameter_group",
        "field_index": 14,
        "encoding": "int32_be",
        "name": "Test Parameter Group - field 14 (not documented yet)",
    },
    "test_param_field_15": {
        "dp_id": 128,
        "code": "test_param_field_15",
        "raw_source": "test_parameter_group",
        "field_index": 15,
        "encoding": "int32_be",
        "name": "Test Parameter Group - field 15 (not documented yet)",
    },
    "test_param_field_16": {
        "dp_id": 128,
        "code": "test_param_field_16",
        "raw_source": "test_parameter_group",
        "field_index": 16,
        "encoding": "int32_be",
        "name": "Test Parameter Group - field 16 (not documented yet)",
    },
    "test_param_field_17": {
        "dp_id": 128,
        "code": "test_param_field_17",
        "raw_source": "test_parameter_group",
        "field_index": 17,
        "encoding": "int32_be",
        "name": "Test Parameter Group - field 17 (not documented yet)",
    },
    "test_param_field_18": {
        "dp_id": 128,
        "code": "test_param_field_18",
        "raw_source": "test_parameter_group",
        "field_index": 18,
        "encoding": "int32_be",
        "name": "Test Parameter Group - field 18 (not documented yet)",
    },
    "test_param_field_19": {
        "dp_id": 128,
        "code": "test_param_field_19",
        "raw_source": "test_parameter_group",
        "field_index": 19,
        "encoding": "int32_be",
        "name": "Test Parameter Group - field 19 (not documented yet)",
    },
})

# --- merge into NUMBER_TYPES (safe even if already defined above) ---
NUMBER_TYPES = globals().get("NUMBER_TYPES", {})
NUMBER_TYPES.update({
    "dhw_temp_setting": {
        "dp_id": 118,
        "code": "dhw_temp_setting",
        "raw_source": "parameter_group_1",
        "field_index": 0,
        "encoding": "int32_be",
        "min_value": 15,
        "max_value": 55,
        "step": 1,
        "name": "DHW temp setting",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "heat_temp_setting": {
        "dp_id": 118,
        "code": "heat_temp_setting",
        "raw_source": "parameter_group_1",
        "field_index": 1,
        "encoding": "int32_be",
        "min_value": 15,
        "max_value": 60,
        "step": 1,
        "name": "Heat temp setting",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "cool_temp_setting": {
        "dp_id": 118,
        "code": "cool_temp_setting",
        "raw_source": "parameter_group_1",
        "field_index": 2,
        "encoding": "int32_be",
        "min_value": 6,
        "max_value": 28,
        "step": 1,
        "name": "Cool temp setting",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "auto_curve_temp_setting": {
        "dp_id": 118,
        "code": "auto_curve_temp_setting",
        "raw_source": "parameter_group_1",
        "field_index": 3,
        "encoding": "int32_be",
        "min_value": 15,
        "max_value": 25,
        "step": 1,
        "name": "Auto (Curve) temp setting",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "auto_min_btw_temp": {
        "dp_id": 118,
        "code": "auto_min_btw_temp",
        "raw_source": "parameter_group_1",
        "field_index": 4,
        "encoding": "int32_be",
        "min_value": 15,
        "max_value": 25,
        "step": 1,
        "name": "Auto Min BTW Temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "auto_max_btw_temp": {
        "dp_id": 118,
        "code": "auto_max_btw_temp",
        "raw_source": "parameter_group_1",
        "field_index": 5,
        "encoding": "int32_be",
        "min_value": 24,
        "max_value": 50,
        "step": 1,
        "name": "Auto Max BTW Temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "dhw_delta_t": {
        "dp_id": 118,
        "code": "dhw_delta_t",
        "raw_source": "parameter_group_1",
        "field_index": 6,
        "encoding": "int32_be",
        "min_value": 1,
        "max_value": 20,
        "step": 1,
        "name": "DHW delta T",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "btw_delta_t": {
        "dp_id": 118,
        "code": "btw_delta_t",
        "raw_source": "parameter_group_1",
        "field_index": 7,
        "encoding": "int32_be",
        "min_value": 1,
        "max_value": 20,
        "step": 1,
        "name": "BTW delta T",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "night_mode_fan_speed": {
        "dp_id": 118,
        "code": "night_mode_fan_speed",
        "raw_source": "parameter_group_1",
        "field_index": 9,
        "encoding": "int32_be",
        "min_value": 30,
        "max_value": 90,
        "step": 1,
        "name": "Night Mode Fan Speed",
        "unit": "rpm",
        "icon": "mdi:fan",
    },
    "night_mode_start_time": {
        "dp_id": 118,
        "code": "night_mode_start_time",
        "raw_source": "parameter_group_1",
        "field_index": 10,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 23,
        "step": 1,
        "name": "Night Mode start time",
        "unit": "H",
    },
    "night_mode_end_time": {
        "dp_id": 118,
        "code": "night_mode_end_time",
        "raw_source": "parameter_group_1",
        "field_index": 11,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 23,
        "step": 1,
        "name": "Night Mode end time",
        "unit": "H",
    },
    "nigth_mode_freq_set": {
        "dp_id": 118,
        "code": "nigth_mode_freq_set",
        "raw_source": "parameter_group_1",
        "field_index": 12,
        "encoding": "int32_be",
        "min_value": 20,
        "max_value": 120,
        "step": 1,
        "name": "Nigth Mode Freq set",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "btw_max_temp": {
        "dp_id": 118,
        "code": "btw_max_temp",
        "raw_source": "parameter_group_1",
        "field_index": 13,
        "encoding": "int32_be",
        "min_value": 50,
        "max_value": 70,
        "step": 1,
        "name": "BTW Max Temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "ec_compressor_model_code": {
        "dp_id": 118,
        "code": "ec_compressor_model_code",
        "raw_source": "parameter_group_1",
        "field_index": 14,
        "encoding": "int32_be",
        "min_value": 1,
        "max_value": 8,
        "step": 1,
        "name": "(EC) Compressor Model Code",
    },
    "ec_compressor_manual_freq": {
        "dp_id": 118,
        "code": "ec_compressor_manual_freq",
        "raw_source": "parameter_group_1",
        "field_index": 16,
        "encoding": "int32_be",
        "min_value": 30,
        "max_value": 90,
        "step": 1,
        "name": "(EC) Compressor Manual Freq",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "ec_dhw_tank_factor": {
        "dp_id": 118,
        "code": "ec_dhw_tank_factor",
        "raw_source": "parameter_group_1",
        "field_index": 17,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 10,
        "step": 1,
        "name": "(EC) DHW Tank factor",
    },
    "ec_exhaust_tp0": {
        "dp_id": 118,
        "code": "ec_exhaust_tp0",
        "raw_source": "parameter_group_1",
        "field_index": 18,
        "encoding": "int32_be",
        "min_value": 50,
        "max_value": 125,
        "step": 1,
        "name": "(EC) Exhaust TP0",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "ec_exhaust_tp1": {
        "dp_id": 118,
        "code": "ec_exhaust_tp1",
        "raw_source": "parameter_group_1",
        "field_index": 19,
        "encoding": "int32_be",
        "min_value": 50,
        "max_value": 125,
        "step": 1,
        "name": "(EC) Exhaust TP1",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "ec_exhaust_tp2": {
        "dp_id": 119,
        "code": "ec_exhaust_tp2",
        "raw_source": "parameter_group_2",
        "field_index": 0,
        "encoding": "int32_be",
        "min_value": 50,
        "max_value": 125,
        "step": 1,
        "name": "(EC) Exhaust TP2",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "ec_exhaust_tp3": {
        "dp_id": 119,
        "code": "ec_exhaust_tp3",
        "raw_source": "parameter_group_2",
        "field_index": 1,
        "encoding": "int32_be",
        "min_value": 50,
        "max_value": 125,
        "step": 1,
        "name": "(EC) Exhaust TP3",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "ec_exhaust_tp4": {
        "dp_id": 119,
        "code": "ec_exhaust_tp4",
        "raw_source": "parameter_group_2",
        "field_index": 2,
        "encoding": "int32_be",
        "min_value": 50,
        "max_value": 125,
        "step": 1,
        "name": "(EC) Exhaust TP4",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "ec_compr_freq_jump_min_1": {
        "dp_id": 119,
        "code": "ec_compr_freq_jump_min_1",
        "raw_source": "parameter_group_2",
        "field_index": 3,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 125,
        "step": 1,
        "name": "(EC) Compr Freq Jump Min 1",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "ec_compr_freq_jump_min_2": {
        "dp_id": 119,
        "code": "ec_compr_freq_jump_min_2",
        "raw_source": "parameter_group_2",
        "field_index": 4,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 125,
        "step": 1,
        "name": "(EC) Compr Freq Jump Min 2",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "ec_compr_freq_jump_min_3": {
        "dp_id": 119,
        "code": "ec_compr_freq_jump_min_3",
        "raw_source": "parameter_group_2",
        "field_index": 5,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 125,
        "step": 1,
        "name": "(EC) Compr Freq Jump Min 3",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "ec_compr_freq_jump_min_4": {
        "dp_id": 119,
        "code": "ec_compr_freq_jump_min_4",
        "raw_source": "parameter_group_2",
        "field_index": 6,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 125,
        "step": 1,
        "name": "(EC) Compr Freq Jump Min 4",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "ec_compr_freq_jump_max_1": {
        "dp_id": 119,
        "code": "ec_compr_freq_jump_max_1",
        "raw_source": "parameter_group_2",
        "field_index": 7,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 125,
        "step": 1,
        "name": "(EC) Compr Freq Jump Max 1",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "ec_compr_freq_jump_max_2": {
        "dp_id": 119,
        "code": "ec_compr_freq_jump_max_2",
        "raw_source": "parameter_group_2",
        "field_index": 8,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 125,
        "step": 1,
        "name": "(EC) Compr Freq Jump Max 2",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "ec_compr_freq_jump_max_3": {
        "dp_id": 119,
        "code": "ec_compr_freq_jump_max_3",
        "raw_source": "parameter_group_2",
        "field_index": 9,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 125,
        "step": 1,
        "name": "(EC) Compr Freq Jump Max 3",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "ec_compr_freq_jump_max_4": {
        "dp_id": 119,
        "code": "ec_compr_freq_jump_max_4",
        "raw_source": "parameter_group_2",
        "field_index": 10,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 125,
        "step": 1,
        "name": "(EC) Compr Freq Jump Max 4",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "ec_compr_max_freq_dhw": {
        "dp_id": 119,
        "code": "ec_compr_max_freq_dhw",
        "raw_source": "parameter_group_2",
        "field_index": 11,
        "encoding": "int32_be",
        "min_value": 30,
        "max_value": 100,
        "step": 1,
        "name": "(EC) Compr max freq DHW",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "ec_compr_max_freq_heat": {
        "dp_id": 119,
        "code": "ec_compr_max_freq_heat",
        "raw_source": "parameter_group_2",
        "field_index": 12,
        "encoding": "int32_be",
        "min_value": 30,
        "max_value": 100,
        "step": 1,
        "name": "(EC) Compr max freq Heat",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "ec_compr_max_freq_cool": {
        "dp_id": 119,
        "code": "ec_compr_max_freq_cool",
        "raw_source": "parameter_group_2",
        "field_index": 13,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 100,
        "step": 1,
        "name": "(EC) Compr max freq Cool",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "ef_dc_fan_sp_manual_select": {
        "dp_id": 119,
        "code": "ef_dc_fan_sp_manual_select",
        "raw_source": "parameter_group_2",
        "field_index": 14,
        "encoding": "int32_be",
        "min_value": 1,
        "max_value": 6,
        "step": 1,
        "name": "(EF) DC FAN sp manual select",
    },
    "ef_dc_fan_speed_1": {
        "dp_id": 119,
        "code": "ef_dc_fan_speed_1",
        "raw_source": "parameter_group_2",
        "field_index": 15,
        "encoding": "int32_be",
        "min_value": 30,
        "max_value": 120,
        "step": 1,
        "name": "(EF) DC FAN speed 1",
        "unit": "rpm",
        "icon": "mdi:fan",
    },
    "ef_dc_fan_speed_2": {
        "dp_id": 119,
        "code": "ef_dc_fan_speed_2",
        "raw_source": "parameter_group_2",
        "field_index": 16,
        "encoding": "int32_be",
        "min_value": 30,
        "max_value": 120,
        "step": 1,
        "name": "(EF) DC FAN speed 2",
        "unit": "rpm",
        "icon": "mdi:fan",
    },
    "ef_dc_fan_speed_3": {
        "dp_id": 119,
        "code": "ef_dc_fan_speed_3",
        "raw_source": "parameter_group_2",
        "field_index": 17,
        "encoding": "int32_be",
        "min_value": 30,
        "max_value": 120,
        "step": 1,
        "name": "(EF) DC FAN speed 3",
        "unit": "rpm",
        "icon": "mdi:fan",
    },
    "ef_dc_fan_speed_4": {
        "dp_id": 119,
        "code": "ef_dc_fan_speed_4",
        "raw_source": "parameter_group_2",
        "field_index": 18,
        "encoding": "int32_be",
        "min_value": 30,
        "max_value": 120,
        "step": 1,
        "name": "(EF) DC FAN speed 4",
        "unit": "rpm",
        "icon": "mdi:fan",
    },
    "ef_dc_fan_speed_5": {
        "dp_id": 119,
        "code": "ef_dc_fan_speed_5",
        "raw_source": "parameter_group_2",
        "field_index": 19,
        "encoding": "int32_be",
        "min_value": 30,
        "max_value": 120,
        "step": 1,
        "name": "(EF) DC FAN speed 5",
        "unit": "rpm",
        "icon": "mdi:fan",
    },
    "ef_dc_fan_speed_6": {
        "dp_id": 120,
        "code": "ef_dc_fan_speed_6",
        "raw_source": "parameter_group_3",
        "field_index": 0,
        "encoding": "int32_be",
        "min_value": 30,
        "max_value": 120,
        "step": 1,
        "name": "(EF) DC FAN speed 6",
        "unit": "rpm",
        "icon": "mdi:fan",
    },
    "ef_evaporator_temp": {
        "dp_id": 120,
        "code": "ef_evaporator_temp",
        "raw_source": "parameter_group_3",
        "field_index": 4,
        "encoding": "int32_be",
        "min_value": -5,
        "max_value": 20,
        "step": 1,
        "name": "(EF) Evaporator Temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "ef_fan_on_deviation": {
        "dp_id": 120,
        "code": "ef_fan_on_deviation",
        "raw_source": "parameter_group_3",
        "field_index": 5,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 30,
        "step": 1,
        "name": "(EF) FAN On Deviation",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "ef_fan_off_deviation": {
        "dp_id": 120,
        "code": "ef_fan_off_deviation",
        "raw_source": "parameter_group_3",
        "field_index": 6,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 30,
        "step": 1,
        "name": "(EF) FAN Off Deviation",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "ef_fan_speed_max": {
        "dp_id": 120,
        "code": "ef_fan_speed_max",
        "raw_source": "parameter_group_3",
        "field_index": 7,
        "encoding": "int32_be",
        "min_value": 10,
        "max_value": 100,
        "step": 1,
        "name": "(EF) Fan speed Max",
        "unit": "rpm",
        "icon": "mdi:fan",
    },
    "ef_fan_speed_min": {
        "dp_id": 120,
        "code": "ef_fan_speed_min",
        "raw_source": "parameter_group_3",
        "field_index": 8,
        "encoding": "int32_be",
        "min_value": 30,
        "max_value": 100,
        "step": 1,
        "name": "(EF) Fan Speed Min",
        "unit": "rpm",
        "icon": "mdi:fan",
    },
    "eeev_eev_initial_step_man": {
        "dp_id": 120,
        "code": "eeev_eev_initial_step_man",
        "raw_source": "parameter_group_3",
        "field_index": 10,
        "encoding": "int32_be",
        "conversion": "value * 2",
        "api_conversion": "value / 2",
        "min_value": 30,
        "max_value": 250,
        "step": 1,
        "name": "(E-EEV) EEV Initial step Man",
        "unit": "step",
        "icon": "mdi:pipe-valve",
    },
    "eeev_eev_adjust_step_man": {
        "dp_id": 120,
        "code": "eeev_eev_adjust_step_man",
        "raw_source": "parameter_group_3",
        "field_index": 11,
        "encoding": "int32_be",
        "conversion": "value * 2",
        "api_conversion": "value / 2",
        "min_value": 15,
        "max_value": 250,
        "step": 1,
        "name": "(E-EEV) EEV Adjust step Man",
        "unit": "step",
        "icon": "mdi:pipe-valve",
    },
    "eeev_eev_man_superheatc_heating": {
        "dp_id": 120,
        "code": "eeev_eev_man_superheatc_heating",
        "raw_source": "parameter_group_3",
        "field_index": 12,
        "encoding": "int32_be",
        "min_value": -20,
        "max_value": 20,
        "step": 1,
        "name": "(E-EEV) EEV Man Superheat/C - Heating",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "eeev_eev_man_superheath_cooling": {
        "dp_id": 120,
        "code": "eeev_eev_man_superheath_cooling",
        "raw_source": "parameter_group_3",
        "field_index": 13,
        "encoding": "int32_be",
        "min_value": -20,
        "max_value": 20,
        "step": 1,
        "name": "(E-EEV) EEV Man Superheat/H - Cooling",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "eeev_discharge_superheat": {
        "dp_id": 120,
        "code": "eeev_discharge_superheat",
        "raw_source": "parameter_group_3",
        "field_index": 14,
        "encoding": "int32_be",
        "min_value": 15,
        "max_value": 40,
        "step": 1,
        "name": "(E-EEV) Discharge Superheat",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "eevi_evi_start_air_temp": {
        "dp_id": 120,
        "code": "eevi_evi_start_air_temp",
        "raw_source": "parameter_group_3",
        "field_index": 16,
        "encoding": "int32_be",
        "min_value": -5,
        "max_value": 20,
        "step": 1,
        "name": "(E-EVI) EVI start air temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "eevi_evi_start_delta_t": {
        "dp_id": 120,
        "code": "eevi_evi_start_delta_t",
        "raw_source": "parameter_group_3",
        "field_index": 17,
        "encoding": "int32_be",
        "min_value": 20,
        "max_value": 60,
        "step": 1,
        "name": "(E-EVI) EVI Start delta T",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "eevi_evi_overheat": {
        "dp_id": 120,
        "code": "eevi_evi_overheat",
        "raw_source": "parameter_group_3",
        "field_index": 18,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 15,
        "step": 1,
        "name": "(E-EVI) EVI Overheat",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "eevi_evi_initial_step_man": {
        "dp_id": 121,
        "code": "eevi_evi_initial_step_man",
        "raw_source": "parameter_group_4",
        "field_index": 0,
        "encoding": "int32_be",
        "min_value": 150,
        "max_value": 500,
        "step": 1,
        "name": "(E-EVI) EVI Initial Step Man",
        "unit": "step",
        "icon": "mdi:pipe-valve",
    },
    "eevi_evi_adjust_step_man": {
        "dp_id": 121,
        "code": "eevi_evi_adjust_step_man",
        "raw_source": "parameter_group_4",
        "field_index": 1,
        "encoding": "int32_be",
        "min_value": 30,
        "max_value": 500,
        "step": 1,
        "name": "(E-EVI) EVI Adjust step Man",
        "unit": "step",
        "icon": "mdi:pipe-valve",
    },
    "edef_defrost_cycle": {
        "dp_id": 121,
        "code": "edef_defrost_cycle",
        "raw_source": "parameter_group_4",
        "field_index": 2,
        "encoding": "int32_be",
        "min_value": 30,
        "max_value": 90,
        "step": 1,
        "name": "(E-DEF) Defrost Cycle",
        "unit": "min",
    },
    "edef_defrost_start_temp": {
        "dp_id": 121,
        "code": "edef_defrost_start_temp",
        "raw_source": "parameter_group_4",
        "field_index": 3,
        "encoding": "int32_be",
        "min_value": -20,
        "max_value": 5,
        "step": 1,
        "name": "(E-DEF) Defrost start temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "edef_defrost_stop_temp": {
        "dp_id": 121,
        "code": "edef_defrost_stop_temp",
        "raw_source": "parameter_group_4",
        "field_index": 4,
        "encoding": "int32_be",
        "min_value": 1,
        "max_value": 30,
        "step": 1,
        "name": "(E-DEF) Defrost stop temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "edef_defrost_max_time": {
        "dp_id": 121,
        "code": "edef_defrost_max_time",
        "raw_source": "parameter_group_4",
        "field_index": 5,
        "encoding": "int32_be",
        "min_value": 1,
        "max_value": 12,
        "step": 1,
        "name": "(E-DEF) Defrost Max time",
        "unit": "min",
    },
    "edef_defrost_delta_t": {
        "dp_id": 121,
        "code": "edef_defrost_delta_t",
        "raw_source": "parameter_group_4",
        "field_index": 6,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 12,
        "step": 1,
        "name": "(E-DEF) Defrost delta T",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "edef_defrost_stop_evap_temp": {
        "dp_id": 121,
        "code": "edef_defrost_stop_evap_temp",
        "raw_source": "parameter_group_4",
        "field_index": 7,
        "encoding": "int32_be",
        "min_value": 1,
        "max_value": 30,
        "step": 1,
        "name": "(E-DEF) Defrost stop Evap temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "edef_defrost_ambient_temp_start": {
        "dp_id": 121,
        "code": "edef_defrost_ambient_temp_start",
        "raw_source": "parameter_group_4",
        "field_index": 8,
        "encoding": "int32_be",
        "min_value": -25,
        "max_value": 5,
        "step": 1,
        "name": "(E-DEF) Defrost Ambient temp start",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "edef_defrost_compr_freq": {
        "dp_id": 121,
        "code": "edef_defrost_compr_freq",
        "raw_source": "parameter_group_4",
        "field_index": 9,
        "encoding": "int32_be",
        "min_value": 20,
        "max_value": 120,
        "step": 1,
        "name": "(E-DEF) Defrost Compr freq",
        "unit": "Hz",
        "icon": "mdi:cosine-wave",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    "eaux_ac_heater_delay": {
        "dp_id": 121,
        "code": "eaux_ac_heater_delay",
        "raw_source": "parameter_group_4",
        "field_index": 10,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 120,
        "step": 1,
        "name": "(E-AUX) AC heater delay",
        "unit": "min",
    },
    "eaux_dhw_dt_start_eh": {
        "dp_id": 121,
        "code": "eaux_dhw_dt_start_eh",
        "raw_source": "parameter_group_4",
        "field_index": 11,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 20,
        "step": 1,
        "name": "(E-AUX) DHW dT start EH",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "eaux_eh_start_delay": {
        "dp_id": 121,
        "code": "eaux_eh_start_delay",
        "raw_source": "parameter_group_4",
        "field_index": 12,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 120,
        "step": 1,
        "name": "(E-AUX) EH start delay",
        "unit": "min",
    },
    "eaux_ac_heater_ambient_temp": {
        "dp_id": 121,
        "code": "eaux_ac_heater_ambient_temp",
        "raw_source": "parameter_group_4",
        "field_index": 15,
        "encoding": "int32_be",
        "min_value": -30,
        "max_value": 50,
        "step": 1,
        "name": "(E-AUX) AC heater Ambient Temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "eaux_ac_heater2_delay": {
        "dp_id": 121,
        "code": "eaux_ac_heater2_delay",
        "raw_source": "parameter_group_4",
        "field_index": 16,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 60,
        "step": 1,
        "name": "(E-AUX) AC heater2 delay",
        "unit": "min",
    },
    "eaux_dhw_heater_ambient_temp": {
        "dp_id": 121,
        "code": "eaux_dhw_heater_ambient_temp",
        "raw_source": "parameter_group_4",
        "field_index": 17,
        "encoding": "int32_be",
        "min_value": -30,
        "max_value": 50,
        "step": 1,
        "name": "(E-AUX) DHW heater Ambient Temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "esol_start_deltat": {
        "dp_id": 122,
        "code": "esol_start_deltat",
        "raw_source": "parameter_group_5",
        "field_index": 0,
        "encoding": "int32_be",
        "min_value": 1,
        "max_value": 30,
        "step": 1,
        "name": "(E-SOL) Start deltaT",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "esol_solar_hysteresis": {
        "dp_id": 122,
        "code": "esol_solar_hysteresis",
        "raw_source": "parameter_group_5",
        "field_index": 1,
        "encoding": "int32_be",
        "min_value": 1,
        "max_value": 10,
        "step": 1,
        "name": "(E-SOL) Solar Hysteresis",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "solar_max_tank_temp": {
        "dp_id": 122,
        "code": "solar_max_tank_temp",
        "raw_source": "parameter_group_5",
        "field_index": 2,
        "encoding": "int32_be",
        "min_value": 50,
        "max_value": 99,
        "step": 1,
        "name": "Solar Max Tank Temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "eoth_spray_valve_start_temp": {
        "dp_id": 122,
        "code": "eoth_spray_valve_start_temp",
        "raw_source": "parameter_group_5",
        "field_index": 4,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 20,
        "step": 1,
        "name": "(E-OTH) Spray Valve start temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "egnd_ground_source_temp_too_low": {
        "dp_id": 122,
        "code": "egnd_ground_source_temp_too_low",
        "raw_source": "parameter_group_5",
        "field_index": 9,
        "encoding": "int32_be",
        "min_value": -15,
        "max_value": 15,
        "step": 1,
        "name": "(E-GND) Ground source temp too low",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "egnd_ground_source_antifreeze_temp": {
        "dp_id": 122,
        "code": "egnd_ground_source_antifreeze_temp",
        "raw_source": "parameter_group_5",
        "field_index": 10,
        "encoding": "int32_be",
        "min_value": -15,
        "max_value": 15,
        "step": 1,
        "name": "(E-GND) Ground source Antifreeze temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "egnd_ground_source_anti_freeze_ambient_t": {
        "dp_id": 122,
        "code": "egnd_ground_source_anti_freeze_ambient_t",
        "raw_source": "parameter_group_5",
        "field_index": 11,
        "encoding": "int32_be",
        "min_value": -15,
        "max_value": 15,
        "step": 1,
        "name": "(E-GND) Ground source anti freeze ambient T",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "ester_sterilization_water_temp": {
        "dp_id": 122,
        "code": "ester_sterilization_water_temp",
        "raw_source": "parameter_group_5",
        "field_index": 13,
        "encoding": "int32_be",
        "min_value": 60,
        "max_value": 90,
        "step": 1,
        "name": "(E-STER) Sterilization Water Temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "ester_sterilization_duration": {
        "dp_id": 122,
        "code": "ester_sterilization_duration",
        "raw_source": "parameter_group_5",
        "field_index": 14,
        "encoding": "int32_be",
        "min_value": 10,
        "max_value": 80,
        "step": 1,
        "name": "(E-STER) Sterilization Duration",
        "unit": "min",
    },
    "ester_sterilization_period": {
        "dp_id": 122,
        "code": "ester_sterilization_period",
        "raw_source": "parameter_group_5",
        "field_index": 15,
        "encoding": "int32_be",
        "min_value": 1,
        "max_value": 99,
        "step": 1,
        "name": "(E-STER) Sterilization Period",
        "unit": "days",
    },
    "ester_sterilization_start_time": {
        "dp_id": 122,
        "code": "ester_sterilization_start_time",
        "raw_source": "parameter_group_5",
        "field_index": 16,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 23,
        "step": 1,
        "name": "(E-STER) Sterilization Start time",
        "unit": "H",
    },
    "ester_sterilization_duration_2": {
        "dp_id": 122,
        "code": "ester_sterilization_duration_2",
        "raw_source": "parameter_group_5",
        "field_index": 17,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 240,
        "step": 1,
        "name": "(E-STER) Sterilization Duration (2, unconfirmed which is which)",
        "unit": "min",
    },
    "eco_btw_heat_set_temp": {
        "dp_id": 122,
        "code": "eco_btw_heat_set_temp",
        "raw_source": "parameter_group_5",
        "field_index": 18,
        "encoding": "int32_be",
        "min_value": 15,
        "max_value": 70,
        "step": 1,
        "name": "(ECO) BTW heat set temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "eco_auto_room_set_temp": {
        "dp_id": 122,
        "code": "eco_auto_room_set_temp",
        "raw_source": "parameter_group_5",
        "field_index": 19,
        "encoding": "int32_be",
        "min_value": 15,
        "max_value": 25,
        "step": 1,
        "name": "(ECO) Auto room set temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "eco_curve_min_btw_temp": {
        "dp_id": 123,
        "code": "eco_curve_min_btw_temp",
        "raw_source": "parameter_group_6",
        "field_index": 0,
        "encoding": "int32_be",
        "min_value": 15,
        "max_value": 25,
        "step": 1,
        "name": "(ECO) Curve min BTW temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "eco_curve_max_btw_temp": {
        "dp_id": 123,
        "code": "eco_curve_max_btw_temp",
        "raw_source": "parameter_group_6",
        "field_index": 1,
        "encoding": "int32_be",
        "min_value": 24,
        "max_value": 55,
        "step": 1,
        "name": "(ECO) Curve max BTW temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "eco_energy_time_of_timer1": {
        "dp_id": 123,
        "code": "eco_energy_time_of_timer1",
        "raw_source": "parameter_group_6",
        "field_index": 2,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 23,
        "step": 1,
        "name": "(ECO) Energy Time of Timer1",
        "unit": "H",
    },
    "eco_energy_time_of_timer2": {
        "dp_id": 123,
        "code": "eco_energy_time_of_timer2",
        "raw_source": "parameter_group_6",
        "field_index": 3,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 23,
        "step": 1,
        "name": "(ECO) Energy Time of Timer2",
        "unit": "H",
    },
    "eco_energy_time_of_timer3": {
        "dp_id": 123,
        "code": "eco_energy_time_of_timer3",
        "raw_source": "parameter_group_6",
        "field_index": 4,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 23,
        "step": 1,
        "name": "(ECO) Energy Time of Timer3",
        "unit": "H",
    },
    "eco_energy_time_of_timer4": {
        "dp_id": 123,
        "code": "eco_energy_time_of_timer4",
        "raw_source": "parameter_group_6",
        "field_index": 5,
        "encoding": "int32_be",
        "min_value": 0,
        "max_value": 23,
        "step": 1,
        "name": "(ECO) Energy Time of Timer4",
        "unit": "H",
    },
    "eco_energy_temp_of_timer1": {
        "dp_id": 123,
        "code": "eco_energy_temp_of_timer1",
        "raw_source": "parameter_group_6",
        "field_index": 6,
        "encoding": "int32_be",
        "min_value": 15,
        "max_value": 70,
        "step": 1,
        "name": "(ECO) Energy Temp. of Timer1",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "eco_energy_temp_of_timer2": {
        "dp_id": 123,
        "code": "eco_energy_temp_of_timer2",
        "raw_source": "parameter_group_6",
        "field_index": 7,
        "encoding": "int32_be",
        "min_value": 15,
        "max_value": 70,
        "step": 1,
        "name": "(ECO) Energy Temp. of Timer2",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "eco_energy_temp_of_timer3": {
        "dp_id": 123,
        "code": "eco_energy_temp_of_timer3",
        "raw_source": "parameter_group_6",
        "field_index": 8,
        "encoding": "int32_be",
        "min_value": 15,
        "max_value": 70,
        "step": 1,
        "name": "(ECO) Energy Temp. of Timer3",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "eco_energy_temp_of_timer4": {
        "dp_id": 123,
        "code": "eco_energy_temp_of_timer4",
        "raw_source": "parameter_group_6",
        "field_index": 9,
        "encoding": "int32_be",
        "min_value": 15,
        "max_value": 70,
        "step": 1,
        "name": "(ECO) Energy Temp. of Timer4",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "param_group_6_field_10": {
        "dp_id": 123,
        "code": "param_group_6_field_10",
        "raw_source": "parameter_group_6",
        "field_index": 10,
        "encoding": "int32_be",
        "step": 1,
        "name": "Parameter Group 6 - field 10 (not documented yet)",
    },
    "param_group_6_field_11": {
        "dp_id": 123,
        "code": "param_group_6_field_11",
        "raw_source": "parameter_group_6",
        "field_index": 11,
        "encoding": "int32_be",
        "step": 1,
        "name": "Parameter Group 6 - field 11 (not documented yet)",
    },
    "param_group_6_field_12": {
        "dp_id": 123,
        "code": "param_group_6_field_12",
        "raw_source": "parameter_group_6",
        "field_index": 12,
        "encoding": "int32_be",
        "step": 1,
        "name": "Parameter Group 6 - field 12 (not documented yet)",
    },
    "param_group_6_field_13": {
        "dp_id": 123,
        "code": "param_group_6_field_13",
        "raw_source": "parameter_group_6",
        "field_index": 13,
        "encoding": "int32_be",
        "step": 1,
        "name": "Parameter Group 6 - field 13 (not documented yet)",
    },
    "param_group_6_field_14": {
        "dp_id": 123,
        "code": "param_group_6_field_14",
        "raw_source": "parameter_group_6",
        "field_index": 14,
        "encoding": "int32_be",
        "step": 1,
        "name": "Parameter Group 6 - field 14 (not documented yet)",
    },
    "param_group_6_field_15": {
        "dp_id": 123,
        "code": "param_group_6_field_15",
        "raw_source": "parameter_group_6",
        "field_index": 15,
        "encoding": "int32_be",
        "step": 1,
        "name": "Parameter Group 6 - field 15 (not documented yet)",
    },
    "param_group_6_field_16": {
        "dp_id": 123,
        "code": "param_group_6_field_16",
        "raw_source": "parameter_group_6",
        "field_index": 16,
        "encoding": "int32_be",
        "step": 1,
        "name": "Parameter Group 6 - field 16 (not documented yet)",
    },
    "param_group_6_field_17": {
        "dp_id": 123,
        "code": "param_group_6_field_17",
        "raw_source": "parameter_group_6",
        "field_index": 17,
        "encoding": "int32_be",
        "step": 1,
        "name": "Parameter Group 6 - field 17 (not documented yet)",
    },
    "param_group_6_field_18": {
        "dp_id": 123,
        "code": "param_group_6_field_18",
        "raw_source": "parameter_group_6",
        "field_index": 18,
        "encoding": "int32_be",
        "step": 1,
        "name": "Parameter Group 6 - field 18 (not documented yet)",
    },
    "param_group_6_field_19": {
        "dp_id": 123,
        "code": "param_group_6_field_19",
        "raw_source": "parameter_group_6",
        "field_index": 19,
        "encoding": "int32_be",
        "step": 1,
        "name": "Parameter Group 6 - field 19 (not documented yet)",
    },
})

# --- merge into SELECT_TYPES (safe even if already defined above) ---
SELECT_TYPES = globals().get("SELECT_TYPES", {})
SELECT_TYPES.update({
    "night_mode_onoff": {
        "dp_id": 118,
        "code": "night_mode_onoff",
        "raw_source": "parameter_group_1",
        "field_index": 8,
        "encoding": "int32_be",
        "options": {
            "1": "OFF",
            "0": "ON",
        },
        "name": "Night Mode ON/OFF",
    },
    "ec_compressor_control_mode": {
        "dp_id": 118,
        "code": "ec_compressor_control_mode",
        "raw_source": "parameter_group_1",
        "field_index": 15,
        "encoding": "int32_be",
        "options": {
            "0": "Auto",
            "1": "Manual",
        },
        "name": "(EC) Compressor Control mode",
    },
    "ef_dc_fan_mode_automan": {
        "dp_id": 120,
        "code": "ef_dc_fan_mode_automan",
        "raw_source": "parameter_group_3",
        "field_index": 1,
        "encoding": "int32_be",
        "options": {
            "0": "Auto",
            "1": "Manual",
        },
        "name": "(EF) DC FAN mode Auto/Man",
    },
    "ef_fan_1_acdc": {
        "dp_id": 120,
        "code": "ef_fan_1_acdc",
        "raw_source": "parameter_group_3",
        "field_index": 2,
        "encoding": "int32_be",
        "options": {
            "1": "AC",
            "0": "DC",
        },
        "name": "(EF) FAN 1 AC/DC",
    },
    "ef_fan_2_acdc": {
        "dp_id": 120,
        "code": "ef_fan_2_acdc",
        "raw_source": "parameter_group_3",
        "field_index": 3,
        "encoding": "int32_be",
        "options": {
            "1": "AC",
            "0": "DC",
        },
        "name": "(EF) FAN 2 AC/DC",
    },
    "eeev_eev_mode_automan": {
        "dp_id": 120,
        "code": "eeev_eev_mode_automan",
        "raw_source": "parameter_group_3",
        "field_index": 9,
        "encoding": "int32_be",
        "options": {
            "1": "Auto",
            "0": "Manual",
        },
        "name": "(E-EEV) EEV Mode Auto/Man",
    },
    "eevi_evi_onoff": {
        "dp_id": 120,
        "code": "eevi_evi_onoff",
        "raw_source": "parameter_group_3",
        "field_index": 15,
        "encoding": "int32_be",
        "options": {
            "0": "ON",
            "1": "Off",
        },
        "name": "(E-EVI) EVI ON/OFF",
    },
    "eevi_evi_mode_automan": {
        "dp_id": 120,
        "code": "eevi_evi_mode_automan",
        "raw_source": "parameter_group_3",
        "field_index": 19,
        "encoding": "int32_be",
        "options": {
            "1": "Auto",
            "0": "Manual",
        },
        "name": "(E-EVI) EVI Mode Auto/Man",
    },
    "eaux_ac_heater_noyes": {
        "dp_id": 121,
        "code": "eaux_ac_heater_noyes",
        "raw_source": "parameter_group_4",
        "field_index": 13,
        "encoding": "int32_be",
        "options": {
            "1": "NO",
            "0": "YES",
        },
        "name": "(E-AUX) AC heater NO/YES",
    },
    "eaux_dhw_heater_noyes": {
        "dp_id": 121,
        "code": "eaux_dhw_heater_noyes",
        "raw_source": "parameter_group_4",
        "field_index": 14,
        "encoding": "int32_be",
        "options": {
            "1": "NO",
            "0": "YES",
        },
        "name": "(E-AUX) DHW heater NO/YES",
    },
    "esol_solar_system_offon": {
        "dp_id": 121,
        "code": "esol_solar_system_offon",
        "raw_source": "parameter_group_4",
        "field_index": 18,
        "encoding": "int32_be",
        "options": {
            "0": "OFF",
            "1": "ON",
        },
        "name": "(E-SOL) Solar System OFF/ON",
    },
    "esol_solar_mode": {
        "dp_id": 121,
        "code": "esol_solar_mode",
        "raw_source": "parameter_group_4",
        "field_index": 19,
        "encoding": "int32_be",
        "options": {
            "0": "Heat",
            "1": "DHW",
            "2": "DHW+Heat",
        },
        "name": "(E-SOL) Solar Mode",
    },
    "eoth_btw_pump_running_mode": {
        "dp_id": 122,
        "code": "eoth_btw_pump_running_mode",
        "raw_source": "parameter_group_5",
        "field_index": 3,
        "encoding": "int32_be",
        "options": {
            "0": "No stop",
            "1": "Stop",
            "2": "Intermittent",
        },
        "name": "(E-OTH) BTW pump running mode",
    },
    "eoth_refrigerant_type": {
        "dp_id": 122,
        "code": "eoth_refrigerant_type",
        "raw_source": "parameter_group_5",
        "field_index": 5,
        "encoding": "int32_be",
        "options": {
            "0": "R32",
            "1": "R410",
            "2": "R290",
        },
        "name": "(E-OTH) Refrigerant type",
    },
    "eoth_low_pressure_sensor": {
        "dp_id": 122,
        "code": "eoth_low_pressure_sensor",
        "raw_source": "parameter_group_5",
        "field_index": 6,
        "encoding": "int32_be",
        "options": {
            "0": "None",
            "1": "Used",
        },
        "name": "(E-OTH) Low Pressure Sensor",
    },
    "eoth_high_pressure_sensor": {
        "dp_id": 122,
        "code": "eoth_high_pressure_sensor",
        "raw_source": "parameter_group_5",
        "field_index": 7,
        "encoding": "int32_be",
        "options": {
            "0": "None",
            "1": "Used",
        },
        "name": "(E-OTH) High Pressure Sensor",
    },
    "egnd_model": {
        "dp_id": 122,
        "code": "egnd_model",
        "raw_source": "parameter_group_5",
        "field_index": 8,
        "encoding": "int32_be",
        "options": {
            "1": "Water to water",
            "0": "Air to water",
        },
        "name": "(E-GND) Model",
    },
    "ester_sterilization_onoff": {
        "dp_id": 122,
        "code": "ester_sterilization_onoff",
        "raw_source": "parameter_group_5",
        "field_index": 12,
        "encoding": "int32_be",
        "options": {
            "0": "On",
            "1": "Off",
        },
        "name": "(E-STER) Sterilization On/Off",
    },
})

