name: Release
on:
  release:
    types: [published]
jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ZIP Component Dir
        run: |
          cd ${{ github.workspace }}/custom_components/tuya_heat_pump
          zip -r tuya_heat_pump.zip ./
      - name: Upload zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/custom_components/tuya_heat_pump/tuya_heat_pump.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
